force-app/main/default/objects/PMHR_Pokemon__c/PMHR_Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Pokemon__c/fields/CaughtForm__c.field-meta.xml
<CustomField>
    <fullName>CaughtForm__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Caught Form</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Pokemons (Caught)</relationshipLabel>
    <relationshipName>CaughtPokemons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
    <label>Form</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Pokemons</relationshipLabel>
    <relationshipName>Pokemons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/PMHR_PokemonData__c.object-meta.xml
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PMHR_TriggerHandlerPokemon.cls
public without sharing class PMHR_TriggerHandlerPokemon implements ITrigger {
    private Map<Id, PMHR_PokemonData__c> relatedPokemonData;

    public void bulkBefore() {
        if (Trigger.isInsert || Trigger.isUpdate) {
            Set<Id> relatedFormsIds = PMHR_Utilities.fetchSObjectListToIdSet(Trigger.new, PMHR_Pokemon__c.Form__c, false);
            relatedFormsIds.addAll(PMHR_Utilities.fetchSObjectListToIdSet(Trigger.new, PMHR_Pokemon__c.CaughtForm__c, false));
            relatedPokemonData = new Map<Id, PMHR_PokemonData__c>(PMHR_TriggerHandlerPokemon_Helper.getRelatedPokemonForms(relatedFormsIds));
        }
    }

    public void bulkAfter() {}

    public void beforeInsert(SObject so) {
        PMHR_Pokemon__c pokemon = (PMHR_Pokemon__c) so;
        PMHR_TriggerHandlerPokemon_Helper.copyCaughtFormToForm(pokemon);
        PMHR_TriggerHandlerPokemon_Helper.validateRegionSpecificVariant(pokemon, relatedPokemonData);
    }

    public void afterInsert(SObject so) {}

    public void beforeUpdate(SObject oldSo, SObject so) {
        PMHR_Pokemon__c pokemon = (PMHR_Pokemon__c) so;
        PMHR_TriggerHandlerPokemon_Helper.copyCaughtFormToForm(pokemon);
        PMHR_TriggerHandlerPokemon_Helper.validateRegionSpecificVariant(pokemon, relatedPokemonData);
    }

    public void afterUpdate(SObject oldSo, SObject so) {}

    public void afterDelete(SObject so) {}

    public void andFinally() {}
}