force-app/main/default/objects/PMHR_Pokemon__c/PMHR_Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Pokemon__c/fields/CaughtForm__c.field-meta.xml
<CustomField>
    <fullName>CaughtForm__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Caught Form</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Pokemons (Caught)</relationshipLabel>
    <relationshipName>CaughtPokemons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
    <label>Form</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Pokemons</relationshipLabel>
    <relationshipName>Pokemons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/PMHR_PokemonData__c.object-meta.xml
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_PokemonData__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/VariantOf__c.field-meta.xml
<CustomField>
    <fullName>VariantOf__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant of</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/PMHR_PokemonRegionalVariant.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Pokemon Regional Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PMHR_TriggerHandlerPokemon_Helper.cls
public class PMHR_TriggerHandlerPokemon_Helper {
    public static List<PMHR_PokemonData__c> getRelatedPokemonForms(Set<Id> pokemonDataIds) {
        return PMHR_PokemonDataQueryService.getPokemonFormsByIds(pokemonDataIds);
    }

    public static void copyCaughtFormToForm(PMHR_Pokemon__c pokemon) {
        if (pokemon.Form__c == null) {
            pokemon = new PMHR_PokemonBuilder(pokemon)
                    .setForm(pokemon.CaughtForm__c)
                    .build();
        }
    }

    public static void validateRegionSpecificVariant(PMHR_Pokemon__c pokemon, Map<Id, PMHR_PokemonData__c> relatedPokemonForms) {
        PMHR_PokemonData__c relatedForm = relatedPokemonForms.get(pokemon.Form__c);
        if (!isRegionSpecificVariantAvailable(relatedForm.Variants__r, pokemon.RegionalVariant__c)) {
            pokemon.RegionalVariant__c.addError(String.format(System.Label.PMHR_Error_Forbidden_Form_Variant, new List<String>{pokemon.RegionalVariant__c}));
        }
    }

    private static Boolean isRegionSpecificVariantAvailable(List<PMHR_PokemonData__c> additionalForms, String regionSpecificVariant) {
        if (regionSpecificVariant == PMHR_Utilities.REGION_VARIANT_STANDARD) {
            return true;
        }
        for (PMHR_PokemonData__c additionalForm : additionalForms) {
            if (additionalForm.RegionalVariant__c == regionSpecificVariant) {
                return true;
            }
        }
        return false;
    }
}