force-app/main/default/objects/PMHR_Pokemon__c/PMHR_Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Pokemon__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/PMHR_PokemonData__c.object-meta.xml
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_PokemonData__c/fields/EvolvesFromVariant__c.field-meta.xml
<CustomField>
    <fullName>EvolvesFromVariant__c</fullName>
    <description>Locks evolving into the form for region specific variants - pokemon region specific variant must correspond with provided value.</description>
    <label>Evolves from Variant</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/FamilyStage__c.field-meta.xml
<CustomField>
    <fullName>FamilyStage__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Family Stage</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PictureUrl__c.field-meta.xml
<CustomField>
    <fullName>PictureUrl__c</fullName>
    <label>Picture Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PokedexNumber__c.field-meta.xml
<CustomField>
    <fullName>PokedexNumber__c</fullName>
    <defaultValue>&apos;000&apos;</defaultValue>
    <externalId>true</externalId>
    <label>Pokedex Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(PrimaryType__c) &amp; IF(NOT(ISBLANK(TEXT(SecondaryType__c))), &apos;/&apos; &amp; TEXT(SecondaryType__c), &apos;&apos;)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/VariantName__c.field-meta.xml
<CustomField>
    <fullName>VariantName__c</fullName>
    <formula>TEXT(RegionalVariant__c) &amp; &apos; &apos; &amp; VariantOf__r.Name</formula>
    <label>Variant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/VariantOf__c.field-meta.xml
<CustomField>
    <fullName>VariantOf__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant of</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/recordTypes/Variant.recordType-meta.xml
<RecordType>
    <fullName>Variant</fullName>
    <active>true</active>
    <description>Additional variant of Pokemon form, like Alolan or Galarian.</description>
    <label>Variant</label>
</RecordType>

force-app/main/default/globalValueSets/PMHR_PokemonRegionalVariant.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Pokemon Regional Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PMHR_EvolvePokemonController.cls
public with sharing class PMHR_EvolvePokemonController {
    @AuraEnabled
    public static List<PokemonNextForm> getNextAvailableForms(Id pokemonId) {
        try {
            PMHR_Pokemon__c pokemon = PMHR_PokemonQueryService.getPokemonWithFormById(pokemonId);
            return getPokemonNextForms(pokemon);
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static void setPokemonForm(Id pokemonId, Id nextFormId, String variant) {
        try {
            new PMHR_PokemonBuilder(new PMHR_Pokemon__c(Id = pokemonId))
                    .setForm(nextFormId)
                    .setRegionSpecificVariant(variant)
                    .save();
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    private static List<PokemonNextForm> getPokemonNextForms(PMHR_Pokemon__c pokemon) {
        List<PokemonNextForm> nextForms = new List<PokemonNextForm>();
        List<PMHR_PokemonData__c> availableNextForms = PMHR_PokemonDataQueryService.getAvailableNextPokemonForms(pokemon);
        if (availableNextForms != null) {
            for (PMHR_PokemonData__c nextForm : availableNextForms) {
                nextForms.addAll(generatePokemonNextForms(pokemon.RegionalVariant__c, nextForm));
            }
        }
        return nextForms;
    }

    private static List<PokemonNextForm> generatePokemonNextForms(String pokemonVariant, PMHR_PokemonData__c nextForm) {
        List<PokemonNextForm> validNextForms = new List<PokemonNextForm>();
        if (nextForm.EvolvesFromVariant__c == pokemonVariant) {
            validNextForms.add(new PokemonNextForm(nextForm));
        }
        for (PMHR_PokemonData__c additionalVariant : nextForm.Variants__r) {
            if (additionalVariant.EvolvesFromVariant__c == pokemonVariant) {
                validNextForms.add(new PokemonNextForm(nextForm, additionalVariant));
            }
        }
        return validNextForms;
    }

    @TestVisible
    private class PokemonNextForm {
        @AuraEnabled public String id { get; private set; }
        @AuraEnabled public String name { get; private set; }
        @AuraEnabled public String pokedexNumber { get; private set; }
        @AuraEnabled public String variant { get; private set; }
        @AuraEnabled public String type { get; private set; }
        @AuraEnabled public Decimal familyStage { get; private set; }
        @AuraEnabled public String pictureUrl { get; private set; }

        public PokemonNextForm(PMHR_PokemonData__c pokemonForm) {
            this.id = pokemonForm.Id;
            this.name = pokemonForm.Name;
            this.pokedexNumber = pokemonForm.PokedexNumber__c;
            this.type = pokemonForm.Type__c;
            this.familyStage = pokemonForm.FamilyStage__c;
            this.pictureUrl = pokemonForm.PictureUrl__c;
        }

        public PokemonNextForm(PMHR_PokemonData__c pokemonForm, PMHR_PokemonData__c variant) {
            this(pokemonForm);
            this.name = variant.VariantName__c;
            this.variant = variant.RegionalVariant__c;
            this.type = variant.Type__c;
            this.pictureUrl = variant.PictureUrl__c;
        }
    }
}