force-app/main/default/objects/PMHR_Pokemon__c/PMHR_Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Pokemon__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
    <label>Form</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Pokemons</relationshipLabel>
    <relationshipName>Pokemons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/IsDeceased__c.field-meta.xml
<CustomField>
    <fullName>IsDeceased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deceased</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/PMHR_PokemonData__c.object-meta.xml
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PictureUrl__c.field-meta.xml
<CustomField>
    <fullName>PictureUrl__c</fullName>
    <label>Picture Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(PrimaryType__c) &amp; IF(NOT(ISBLANK(TEXT(SecondaryType__c))), &apos;/&apos; &amp; TEXT(SecondaryType__c), &apos;&apos;)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/VariantOf__c.field-meta.xml
<CustomField>
    <fullName>VariantOf__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant of</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/PMHR_PokemonRegionalVariant.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Pokemon Regional Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/lwcControllers/PMHR_PokemonPictureController.cls
public class PMHR_PokemonPictureController {
    @AuraEnabled
    public static PokemonPicture getPokemonPicture(Id pokemonId) {
        PMHR_Pokemon__c pokemon = PMHR_PokemonQueryService.getPokemonWithFormById(pokemonId);
        PMHR_PokemonData__c pokemonForm = PMHR_PokemonDataQueryService.getPokemonFormById(pokemon.Form__c);
        return new PokemonPicture(pokemonForm, pokemon.IsDeceased__c, pokemon.RegionalVariant__c);
    }

    @TestVisible
    private Class PokemonPicture {
        @AuraEnabled public String pictureUrl { get; private set; }
        @AuraEnabled public String pokemonType { get; private set; }
        @AuraEnabled public Boolean isDead { get; private set; }

        public PokemonPicture (PMHR_PokemonData__c pokemonForm, Boolean isDead, String regionSpecificVariant) {
            this.isDead = isDead;
            if (regionSpecificVariant == PMHR_Utilities.REGION_VARIANT_STANDARD) {
                this.pictureUrl = pokemonForm.PictureUrl__c;
                this.pokemonType = pokemonForm.Type__c;
            } else {
                this.setFieldsFromAdditionalVariant(pokemonForm.Variants__r, regionSpecificVariant);
            }
        }

        private void setFieldsFromAdditionalVariant(List<PMHR_PokemonData__c> additionalVariants, String regionSpecificVariant) {
            for (PMHR_PokemonData__c additionalForm : additionalVariants) {
                if (additionalForm.RegionalVariant__c == regionSpecificVariant) {
                    this.pictureUrl = additionalForm.PictureUrl__c;
                    this.pokemonType = additionalForm.Type__c;
                    return;
                }
            }
        }
    }
}