src/objects/Nuzlocke__c.object
<CustomObject>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pokemon__c.object
<CustomObject>
    <fields>
        <fullName>Catch_Method__c</fullName>
        <label>Catch Method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Breeding</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Fossil</fullName>
                </value>
                <value>
                    <fullName>Game Corner</fullName>
                </value>
                <value>
                    <fullName>Headbutt</fullName>
                </value>
                <value>
                    <fullName>Land</fullName>
                </value>
                <value>
                    <fullName>Starter</fullName>
                </value>
                <value>
                    <fullName>Trade</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Caught_Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Caught Form</label>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons (Caught)</relationshipLabel>
        <relationshipName>Caught_Pokemons</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cause_of_Death__c</fullName>
        <label>Cause of Death</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Death_Level__c</fullName>
        <label>Death Level</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Death__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Death</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
        <label>Form</label>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Genderless</fullName>
                    <default>true</default>
                    <label>Genderless</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Catch Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Pokemon__c.object
    <fields>
        <fullName>Region_Specific_Variant__c</fullName>
        <label>Region Specific Variant</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>

src/globalValueSets/Region_Specific_Pokemon_Variants.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Region Specific Pokemon Variants</masterLabel>
</GlobalValueSet>

src/classes/PMHR_PokemonBuilder.cls
public with sharing class PMHR_PokemonBuilder {
    public static final String CATCH_METHOD_EVENT = 'Event';

    public static final String REGION_VARIANT_ALOLAN = 'Alolan';

    private Pokemon__c record;

    private Pokemon__c defaultData() {
        return new Pokemon__c(
                Name = 'Default Pokemon',
                Gender__c = PMHR_Utilities.GENDER_MALE,
                Catch_Method__c = 'Route 1'
        );
    }

    public PMHR_PokemonBuilder() {
        this.record = this.defaultData();
    }

    public PMHR_PokemonBuilder(Pokemon__c record) {
        this.record = record;
    }

    public PMHR_PokemonBuilder reset() {
        this.record = this.defaultData();
        return this;
    }

    public Pokemon__c build() {
        Pokemon__c record = this.record;
        this.reset();
        return record;
    }

    public Pokemon__c save() {
        Pokemon__c record = this.build();
        upsert record;
        return record;
    }

    public PMHR_PokemonBuilder setName(String name) {
        this.record.Name = name;
        return this;
    }

    public PMHR_PokemonBuilder setNuzlocke(Id nuzlockeId) {
        this.record.Nuzlocke__c = nuzlockeId;
        return this;
    }

    public PMHR_PokemonBuilder setCaughtForm(Id pokemonId) {
        this.record.Caught_Form__c = pokemonId;
        return this;
    }

    public PMHR_PokemonBuilder setForm(Id pokemonId) {
        this.record.Form__c = pokemonId;
        return this;
    }

    public PMHR_PokemonBuilder setCatchMethod(String catchMethod) {
        this.record.Catch_Method__c = catchMethod;
        return this;
    }

    public PMHR_PokemonBuilder setCatchLocation(String catchLocation) {
        this.record.Location__c = catchLocation;
        return this;
    }

    public PMHR_PokemonBuilder setDeath(Boolean isDead) {
        this.record.Death__c = isDead;
        return this;
    }

    public PMHR_PokemonBuilder setDeathCause(String cause) {
        this.record.Cause_of_Death__c = cause;
        return this;
    }

    public PMHR_PokemonBuilder setDeathLevel(Integer deathLevel) {
        this.record.Death_Level__c = Decimal.valueOf(deathLevel);
        return this;
    }

    public PMHR_PokemonBuilder setGender(String gender) {
        this.record.Gender__c = gender;
        return this;
    }

    public PMHR_PokemonBuilder setRegionSpecificVariant(String variant) {
        this.record.Region_Specific_Variant__c = variant;
        return this;
    }
}