src/objects/Pokemon__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
        <label>Form</label>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pokemon_Data__c.object
<CustomObject>
    <fields>
        <fullName>Family_Stage__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Family Stage</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abra</fullName>
                </value>
                <value>
                    <fullName>Absol</fullName>
                </value>
                <value>
                    <fullName>Aerodactyl</fullName>
                </value>
                <value>
                    <fullName>Aipom</fullName>
                </value>
                <value>
                    <fullName>Alomomola</fullName>
                </value>
                <value>
                    <fullName>Amaura</fullName>
                </value>
                <value>
                    <fullName>Anorith</fullName>
                </value>
                <value>
                    <fullName>Arceus</fullName>
                </value>
                <value>
                    <fullName>Archen</fullName>
                </value>
                <value>
                    <fullName>Aron</fullName>
                </value>
                <value>
                    <fullName>Articuno</fullName>
                </value>
                <value>
                    <fullName>Audino</fullName>
                </value>
                <value>
                    <fullName>Axew</fullName>
                </value>
                <value>
                    <fullName>Azelf</fullName>
                </value>
                <value>
                    <fullName>Azurill</fullName>
                </value>
                <value>
                    <fullName>Bagon</fullName>
                </value>
                <value>
                    <fullName>Baltoy</fullName>
                </value>
                <value>
                    <fullName>Barboach</fullName>
                </value>
                <value>
                    <fullName>Basculin</fullName>
                </value>
                <value>
                    <fullName>Beldum</fullName>
                </value>
                <value>
                    <fullName>Bellsprout</fullName>
                </value>
                <value>
                    <fullName>Bergmite</fullName>
                </value>
                <value>
                    <fullName>Bidoof</fullName>
                </value>
                <value>
                    <fullName>Binacle</fullName>
                </value>
                <value>
                    <fullName>Blacephalon</fullName>
                </value>
                <value>
                    <fullName>Blitzle</fullName>
                </value>
                <value>
                    <fullName>Bonsly</fullName>
                </value>
                <value>
                    <fullName>Bouffalant</fullName>
                </value>
                <value>
                    <fullName>Bounsweet</fullName>
                </value>
                <value>
                    <fullName>Bronzor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pokedex_Number__c</fullName>
        <defaultValue>TEXT(000)</defaultValue>
        <externalId>true</externalId>
        <label>Pokedex Number</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PMHR_NextFormController.cls
public class PMHR_NextFormController {
    @AuraEnabled
    public static PokemonWithNextForms getNextAvailableForms(String pokemonId) {
        try {
            Pokemon__c pokemon = [SELECT Name, Form__r.Family__c, Form__r.Family_Stage__c FROM Pokemon__c WHERE Id = :pokemonId LIMIT 1];
            List<Pokemon_Data__c> nextAvailableForms = [SELECT Id, Name, Pokedex_Number__c, Family_Stage__c FROM Pokemon_Data__c WHERE Family__c = :pokemon.Form__r.Family__c AND Family_Stage__c > :pokemon.Form__r.Family_Stage__c AND Family_Stage__c <= :pokemon.Form__r.Family_Stage__c + 1 ORDER BY Pokedex_Number__c LIMIT 20];
            return new PokemonWithNextForms(pokemon, nextAvailableForms);
        } catch (Exception ex) {
            System.debug(ex.getMessage());
        }
        return null;
    }

    @AuraEnabled
    public static void setPokemonForm(String pokemonId, String nextFormId) {
        try {
            Pokemon__c pokemon = [SELECT Form__c FROM Pokemon__c WHERE Id = :pokemonId LIMIT 1];
            pokemon.Form__c = nextFormId;
            update pokemon;
        } catch (DmlException ex) {
            System.debug(ex.getDmlMessage(0));
        } catch (Exception ex) {
            System.debug(ex.getMessage());
        }
    }

    @TestVisible
    private class PokemonWithNextForms {
        @AuraEnabled public String name { get; private set; }
        @AuraEnabled public Decimal stage { get; private set; }
        @AuraEnabled public List<Pokemon_Data__c> nextForms { get; private set; }

        public PokemonWithNextForms(Pokemon__c pokemon, List<Pokemon_Data__c> nextAvailableForms) {
            this.name = pokemon.Name;
            this.stage = pokemon.Form__r.Family_Stage__c;
            this.nextForms = nextAvailableForms;
        }
    }
}