src/objects/Pokemon__c.object
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Pokemon__c.object
    <fields>
        <fullName>Region_Specific_Variant__c</fullName>
        <label>Region Specific Variant</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>

src/globalValueSets/Region_Specific_Pokemon_Variants.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Region Specific Pokemon Variants</masterLabel>
</GlobalValueSet>

src/classes/PMHR_Utilities.cls
public class PMHR_Utilities {
    public static final String GENDER_MALE = 'Male';

    public static final List<PicklistEntry> POKEMON_REGIONAL_VARIANT = Pokemon__c.Region_Specific_Variant__c.getDescribe().getPicklistValues();

    public static List<String> getPokemonRegionalVariantsValues() {
        List<String> regionSpecificVariants = new List<String>();
        for (PicklistEntry variant : PMHR_Utilities.POKEMON_REGIONAL_VARIANT) {
            regionSpecificVariants.add(variant.getValue());
        }
        return regionSpecificVariants;
    }

    public static Set<Id> fetchSObjectListToIdSet(List<SObject> sObjectList, SObjectField field) {
        String fieldName = field.getDescribe().getName();
        Set<Id> result = new Set<Id>();
        for (SObject so : sObjectList) {
            result.add((Id) so.get(fieldName));
        }
        return result;
    }
}