src/objects/Pokemon_Data__c.object
<CustomObject>
    <fields>
        <fullName>Family_Stage__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Family Stage</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abra</fullName>
                </value>
                <value>
                    <fullName>Absol</fullName>
                </value>
                <value>
                    <fullName>Aerodactyl</fullName>
                </value>
                <value>
                    <fullName>Aipom</fullName>
                </value>
                <value>
                    <fullName>Alomomola</fullName>
                </value>
                <value>
                    <fullName>Amaura</fullName>
                </value>
                <value>
                    <fullName>Anorith</fullName>
                </value>
                <value>
                    <fullName>Arceus</fullName>
                </value>
                <value>
                    <fullName>Archen</fullName>
                </value>
                <value>
                    <fullName>Aron</fullName>
                </value>
                <value>
                    <fullName>Articuno</fullName>
                </value>
                <value>
                    <fullName>Audino</fullName>
                </value>
                <value>
                    <fullName>Axew</fullName>
                </value>
                <value>
                    <fullName>Azelf</fullName>
                </value>
                <value>
                    <fullName>Azurill</fullName>
                </value>
                <value>
                    <fullName>Bagon</fullName>
                </value>
                <value>
                    <fullName>Baltoy</fullName>
                </value>
                <value>
                    <fullName>Barboach</fullName>
                </value>
                <value>
                    <fullName>Basculin</fullName>
                </value>
                <value>
                    <fullName>Beldum</fullName>
                </value>
                <value>
                    <fullName>Bellsprout</fullName>
                </value>
                <value>
                    <fullName>Bergmite</fullName>
                </value>
                <value>
                    <fullName>Bidoof</fullName>
                </value>
                <value>
                    <fullName>Binacle</fullName>
                </value>
                <value>
                    <fullName>Blacephalon</fullName>
                </value>
                <value>
                    <fullName>Blitzle</fullName>
                </value>
                <value>
                    <fullName>Bonsly</fullName>
                </value>
                <value>
                    <fullName>Bouffalant</fullName>
                </value>
                <value>
                    <fullName>Bounsweet</fullName>
                </value>
                <value>
                    <fullName>Bronzor</fullName>
                </value>
                <value>
                    <fullName>Bulbasaur</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Picture_Url__c</fullName>
        <label>Picture Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Pokedex_Number__c</fullName>
        <defaultValue>TEXT(000)</defaultValue>
        <externalId>true</externalId>
        <label>Pokedex Number</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Type__c</fullName>
        <label>Primary Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pokemon_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region_Specific_Variants__c</fullName>
        <description>Does the Pokemon has any region specific variant?</description>
        <label>Available Region Specific Variants</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alolan</fullName>
                </value>
                <value>
                    <fullName>Galarian</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Type__c</fullName>
        <label>Secondary Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pokemon_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Pokemon_Data__c.object
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <description>Standard form of the Pokemon species</description>
        <label>Form</label>
    </recordTypes>

force-app/main/default/globalValueSets/Pokemon_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>???</fullName>
    </customValue>
    <customValue>
        <fullName>Bug</fullName>
    </customValue>
    <customValue>
        <fullName>Dark</fullName>
    </customValue>
    <customValue>
        <fullName>Dragon</fullName>
    </customValue>
    <customValue>
        <fullName>Electric</fullName>
    </customValue>
    <customValue>
        <fullName>Fairy</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>Fire</fullName>
    </customValue>
    <customValue>
        <fullName>Flying</fullName>
    </customValue>
    <customValue>
        <fullName>Ghost</fullName>
    </customValue>
    <customValue>
        <fullName>Grass</fullName>
    </customValue>
    <customValue>
        <fullName>Ground</fullName>
    </customValue>
    <customValue>
        <fullName>Ice</fullName>
    </customValue>
    <customValue>
        <fullName>Normal</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Psychic</fullName>
    </customValue>
    <customValue>
        <fullName>Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Steel</fullName>
    </customValue>
    <customValue>
        <fullName>Water</fullName>
    </customValue>
    <description>List of all Pokemon types</description>
    <masterLabel>Pokemon Type</masterLabel>
</GlobalValueSet>

src/classes/PMHR_PokemonDataBuilder_Test.cls
@IsTest
private class PMHR_PokemonDataBuilder_Test {
    static testMethod void shouldBuildPokemonData() {
        //given
        String form = 'Bulbasaur';
        String pokedexNumber = '001';
        Integer familyStage = 1;
        String pictureUrl = 'https://test.picture.com';

        List<String> regionSpecificVariants = PMHR_Utilities.getPokemonRegionalVariantsValues();

        //when
        Pokemon_Data__c pokemonData = new PMHR_PokemonDataBuilder()
                .setPokedexNumber(pokedexNumber)
                .setForm(form)
                .setFamily(form)
                .setFamilyStage(familyStage)
                .setPrimaryType(PMHR_PokemonDataBuilder.TYPE_NORMAL)
                .setSecondaryType(PMHR_PokemonDataBuilder.TYPE_DARK)
                .setPictureUrl(pictureUrl)
                .setRegionSpecificVariants(regionSpecificVariants)
                .save();

        //then
        pokemonData = PMHR_PokemonDataQueryService.getPokemonDataById(pokemonData.Id);
        System.assertEquals(form, pokemonData.Name);
        System.assertEquals(pokedexNumber, pokemonData.Pokedex_Number__c);
        System.assertEquals(form, pokemonData.Family__c);
        System.assertEquals(familyStage, Integer.valueOf(pokemonData.Family_Stage__c));
        System.assertEquals(PMHR_PokemonDataBuilder.TYPE_NORMAL, pokemonData.Primary_Type__c);
        System.assertEquals(PMHR_PokemonDataBuilder.TYPE_DARK, pokemonData.Secondary_Type__c);
        System.assertEquals(pictureUrl, pokemonData.Picture_Url__c);
        System.assertEquals(pictureUrl, pokemonData.Picture_Url__c);
        for (String variant : regionSpecificVariants) {
            System.assert(pokemonData.Region_Specific_Variants__c.contains(variant));
        }
    }

    static testMethod void shouldThrowExceptionNullRegionVariants() {
        //given
        Boolean errorOccurred = false;

        //when
        try {
            Pokemon_Data__c pokemonData = new PMHR_PokemonDataBuilder()
                    .setRegionSpecificVariants(null)
                    .build();
        } catch (PMHR_PokemonDataBuilder.NullRegionSpecificVariantsException ex) {
            errorOccurred = true;
        }

        //then
        System.assert(errorOccurred);
    }
}