src/objects/Pokemon__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
        <label>Form</label>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Pokemon__c.object
    <fields>
        <fullName>Region_Specific_Variant__c</fullName>
        <label>Region Specific Variant</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>

src/objects/Pokemon_Data__c.object
<CustomObject>
    <fields>
        <fullName>Family_Stage__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Family Stage</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abra</fullName>
                </value>
                <value>
                    <fullName>Absol</fullName>
                </value>
                <value>
                    <fullName>Aerodactyl</fullName>
                </value>
                <value>
                    <fullName>Aipom</fullName>
                </value>
                <value>
                    <fullName>Alomomola</fullName>
                </value>
                <value>
                    <fullName>Amaura</fullName>
                </value>
                <value>
                    <fullName>Anorith</fullName>
                </value>
                <value>
                    <fullName>Arceus</fullName>
                </value>
                <value>
                    <fullName>Archen</fullName>
                </value>
                <value>
                    <fullName>Aron</fullName>
                </value>
                <value>
                    <fullName>Articuno</fullName>
                </value>
                <value>
                    <fullName>Audino</fullName>
                </value>
                <value>
                    <fullName>Axew</fullName>
                </value>
                <value>
                    <fullName>Azelf</fullName>
                </value>
                <value>
                    <fullName>Azurill</fullName>
                </value>
                <value>
                    <fullName>Bagon</fullName>
                </value>
                <value>
                    <fullName>Baltoy</fullName>
                </value>
                <value>
                    <fullName>Barboach</fullName>
                </value>
                <value>
                    <fullName>Basculin</fullName>
                </value>
                <value>
                    <fullName>Beldum</fullName>
                </value>
                <value>
                    <fullName>Bellsprout</fullName>
                </value>
                <value>
                    <fullName>Bergmite</fullName>
                </value>
                <value>
                    <fullName>Bidoof</fullName>
                </value>
                <value>
                    <fullName>Binacle</fullName>
                </value>
                <value>
                    <fullName>Blacephalon</fullName>
                </value>
                <value>
                    <fullName>Blitzle</fullName>
                </value>
                <value>
                    <fullName>Bonsly</fullName>
                </value>
                <value>
                    <fullName>Bouffalant</fullName>
                </value>
                <value>
                    <fullName>Bounsweet</fullName>
                </value>
                <value>
                    <fullName>Bronzor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Picture_Url__c</fullName>
        <label>Picture Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Pokedex_Number__c</fullName>
        <defaultValue>TEXT(000)</defaultValue>
        <externalId>true</externalId>
        <label>Pokedex Number</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Type__c</fullName>
        <label>Primary Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pokemon_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Type__c</fullName>
        <label>Secondary Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pokemon_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(Primary_Type__c) &amp; IF(NOT(ISBLANK(TEXT(Secondary_Type__c))), &apos;/&apos; &amp; TEXT(Secondary_Type__c), &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Pokemon_Data__c.object
    <fields>
        <fullName>Region_Specific_Variant__c</fullName>
        <label>Region Specific Variant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>

temp/objects/Pokemon_Data__c.object
    <fields>
        <fullName>Variant_Name__c</fullName>
        <formula>TEXT(Region_Specific_Variant__c) &amp; &apos; &apos; &amp; Variant_Of__r.Name</formula>
        <label>Variant Name</label>
        <type>Text</type>
    </fields>

temp/objects/Pokemon_Data__c.object
    <fields>
        <fullName>Variant_Of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Variant Of</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Pokemon_Data__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Additional Variants</relationshipLabel>
        <relationshipName>Additional_Variants</relationshipName>
        <type>Lookup</type>
    </fields>

force-app/main/default/globalValueSets/Pokemon_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>???</fullName>
    </customValue>
    <customValue>
        <fullName>Bug</fullName>
    </customValue>
    <customValue>
        <fullName>Dark</fullName>
    </customValue>
    <customValue>
        <fullName>Dragon</fullName>
    </customValue>
    <customValue>
        <fullName>Electric</fullName>
    </customValue>
    <customValue>
        <fullName>Fairy</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>Fire</fullName>
    </customValue>
    <customValue>
        <fullName>Flying</fullName>
    </customValue>
    <customValue>
        <fullName>Ghost</fullName>
    </customValue>
    <customValue>
        <fullName>Grass</fullName>
    </customValue>
    <customValue>
        <fullName>Ground</fullName>
    </customValue>
    <customValue>
        <fullName>Ice</fullName>
    </customValue>
    <customValue>
        <fullName>Normal</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Psychic</fullName>
    </customValue>
    <customValue>
        <fullName>Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Steel</fullName>
    </customValue>
    <customValue>
        <fullName>Water</fullName>
    </customValue>
    <description>List of all Pokemon types</description>
    <masterLabel>Pokemon Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Region_Specific_Pokemon_Variants.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Region Specific Pokemon Variants</masterLabel>
</GlobalValueSet>

src/classes/PMHR_PokemonDataQueryService.cls
public with sharing class PMHR_PokemonDataQueryService {
    public static Pokemon_Data__c getPokemonFormById(Id pokemonDataId) {
        return getPokemonFormsByIds(new Set<Id>{pokemonDataId}).get(0);
    }

    public static List<Pokemon_Data__c> getPokemonFormsByIds(Set<Id> pokemonDataIds) {
        return [
                SELECT Id, Name, Pokedex_Number__c, Family__c, Family_Stage__c, Type__c, Primary_Type__c, Secondary_Type__c, Picture_Url__c,
                    (SELECT Id, Variant_Name__c, Region_Specific_Variant__c, Type__c, Picture_Url__c
                    FROM Additional_Variants__r)
                FROM Pokemon_Data__c
                WHERE Id IN :pokemonDataIds
                AND RecordTypeId = :PMHR_Utilities.getRecordTypeIdByName(SObjectType.Pokemon_Data__c, PMHR_PokemonDataBuilder.RT_FORM)
        ];
    }

    public static List<Pokemon_Data__c> getAvailableNextPokemonForms(Pokemon__c pokemon) {
        return [
                SELECT Id, Name, Pokedex_Number__c, Family_Stage__c,
                    (SELECT Id, Variant_Name__c, Region_Specific_Variant__c
                    FROM Additional_Variants__r)
                FROM Pokemon_Data__c
                WHERE Family__c = :pokemon.Form__r.Family__c
                AND Family_Stage__c = :pokemon.Form__r.Family_Stage__c + 1
                AND RecordTypeId = :PMHR_Utilities.getRecordTypeIdByName(SObjectType.Pokemon_Data__c, PMHR_PokemonDataBuilder.RT_FORM)
                ORDER BY Pokedex_Number__c ASC
                LIMIT 20
        ];
    }

    public static Pokemon_Data__c getAdditionalVariantById(Id additionalVariantId) {
        return [
                SELECT Id, Name, Variant_Name__c, Variant_Of__c, Primary_Type__c, Secondary_Type__c, Type__c,
                        Picture_Url__c, Region_Specific_Variant__c
                FROM Pokemon_Data__c
                WHERE Id = :additionalVariantId
                AND RecordTypeId = :PMHR_Utilities.getRecordTypeIdByName(SObjectType.Pokemon_Data__c, PMHR_PokemonDataBuilder.RT_ADDITIONAL_VARIANT)
                LIMIT 1
        ];
    }

    public static List<Pokemon_Data__c> getAdditionalVariantByFormIds(Set<Id> formIds) {
        return [
                SELECT Id, Name, Variant_Name__c, Variant_Of__c, Primary_Type__c, Secondary_Type__c, Type__c,
                        Picture_Url__c, Region_Specific_Variant__c
                FROM Pokemon_Data__c
                WHERE Variant_Of__c IN :formIds
                AND RecordTypeId = :PMHR_Utilities.getRecordTypeIdByName(SObjectType.Pokemon_Data__c, PMHR_PokemonDataBuilder.RT_ADDITIONAL_VARIANT)
        ];
    }

    public static List<Pokemon_Data__c> getPokemonFormByIdsOrPokedexNumbers(Set<Id> ids, Set<String> pokedexNumbers) {
        return [
                SELECT Id, Name, Pokedex_Number__c, Family__c, Family_Stage__c, Type__c, Primary_Type__c, Secondary_Type__c, Picture_Url__c,
                    (SELECT Id, Name, Variant_Name__c, Variant_Of__c, Primary_Type__c, Secondary_Type__c, Type__c,
                            Picture_Url__c, Region_Specific_Variant__c
                    FROM Additional_Variants__r)
                FROM Pokemon_Data__c
                WHERE (Id IN :ids
                OR Pokedex_Number__c IN :pokedexNumbers)
                AND RecordTypeId = :PMHR_Utilities.getRecordTypeIdByName(SObjectType.Pokemon_Data__c, PMHR_PokemonDataBuilder.RT_FORM)
        ];
    }
}