src/objects/Pokemon_Data__c.object
<CustomObject>
    <fields>
        <fullName>Family_Stage__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Family Stage</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abra</fullName>
                </value>
                <value>
                    <fullName>Absol</fullName>
                </value>
                <value>
                    <fullName>Aerodactyl</fullName>
                </value>
                <value>
                    <fullName>Aipom</fullName>
                </value>
                <value>
                    <fullName>Alomomola</fullName>
                </value>
                <value>
                    <fullName>Amaura</fullName>
                </value>
                <value>
                    <fullName>Anorith</fullName>
                </value>
                <value>
                    <fullName>Arceus</fullName>
                </value>
                <value>
                    <fullName>Archen</fullName>
                </value>
                <value>
                    <fullName>Aron</fullName>
                </value>
                <value>
                    <fullName>Articuno</fullName>
                </value>
                <value>
                    <fullName>Audino</fullName>
                </value>
                <value>
                    <fullName>Axew</fullName>
                </value>
                <value>
                    <fullName>Azelf</fullName>
                </value>
                <value>
                    <fullName>Azurill</fullName>
                </value>
                <value>
                    <fullName>Bagon</fullName>
                </value>
                <value>
                    <fullName>Baltoy</fullName>
                </value>
                <value>
                    <fullName>Barboach</fullName>
                </value>
                <value>
                    <fullName>Basculin</fullName>
                </value>
                <value>
                    <fullName>Beldum</fullName>
                </value>
                <value>
                    <fullName>Bellsprout</fullName>
                </value>
                <value>
                    <fullName>Bergmite</fullName>
                </value>
                <value>
                    <fullName>Bidoof</fullName>
                </value>
                <value>
                    <fullName>Binacle</fullName>
                </value>
                <value>
                    <fullName>Blacephalon</fullName>
                </value>
                <value>
                    <fullName>Blitzle</fullName>
                </value>
                <value>
                    <fullName>Bonsly</fullName>
                </value>
                <value>
                    <fullName>Bouffalant</fullName>
                </value>
                <value>
                    <fullName>Bounsweet</fullName>
                </value>
                <value>
                    <fullName>Bronzor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pokedex_Number__c</fullName>
        <defaultValue>TEXT(000)</defaultValue>
        <externalId>true</externalId>
        <label>Pokedex Number</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Type__c</fullName>
        <label>Primary Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pokemon_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Pokemon_Data__c.object
    <fields>
        <fullName>Evolves_from_Variant__c</fullName>
        <description>Locks evolving into the form for region specific variants - pokemon region specific variant must correspond with provided value.</description>
        <label>Evolves from Variant</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>

force-app/main/default/globalValueSets/Pokemon_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>???</fullName>
    </customValue>
    <customValue>
        <fullName>Bug</fullName>
    </customValue>
    <customValue>
        <fullName>Dark</fullName>
    </customValue>
    <customValue>
        <fullName>Dragon</fullName>
    </customValue>
    <customValue>
        <fullName>Electric</fullName>
    </customValue>
    <customValue>
        <fullName>Fairy</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>Fire</fullName>
    </customValue>
    <customValue>
        <fullName>Flying</fullName>
    </customValue>
    <customValue>
        <fullName>Ghost</fullName>
    </customValue>
    <customValue>
        <fullName>Grass</fullName>
    </customValue>
    <customValue>
        <fullName>Ground</fullName>
    </customValue>
    <customValue>
        <fullName>Ice</fullName>
    </customValue>
    <customValue>
        <fullName>Normal</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Psychic</fullName>
    </customValue>
    <customValue>
        <fullName>Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Steel</fullName>
    </customValue>
    <customValue>
        <fullName>Water</fullName>
    </customValue>
    <description>List of all Pokemon types</description>
    <masterLabel>Pokemon Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Region_Specific_Pokemon_Variants.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Region Specific Pokemon Variants</masterLabel>
</GlobalValueSet>

src/classes/PMHR_PokemonFormBuilder.cls
public with sharing class PMHR_PokemonFormBuilder extends PMHR_PokemonDataBuilder {
    protected override Pokemon_Data__c defaultData() {
        return new Pokemon_Data__c(
                Pokedex_Number__c = '001',
                Name = 'Default Pokemon',
                Primary_Type__c = TYPE_NORMAL,
                Family__c = 'Default Pokemon',
                Family_Stage__c = 1,
                RecordTypeId = PMHR_Utilities.getRecordTypeIdByName(SObjectType.Pokemon_Data__c, PMHR_PokemonDataBuilder.RT_FORM),
                Evolves_from_Variant__c = PMHR_Utilities.REGION_VARIANT_STANDARD
        );
    }

    public PMHR_PokemonFormBuilder() {
        super();
    }

    public PMHR_PokemonFormBuilder(Pokemon_Data__c pokemonDataRecord) {
        super(pokemonDataRecord);
    }
}