src/objects/Pokemon__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
        <label>Form</label>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Variant__c</fullName>
        <label>Variant</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                    <label>Standard</label>
                </value>
                <value>
                    <fullName>Alolan</fullName>
                </value>
                <value>
                    <fullName>Galarian</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pokemon_Data__c.object
<CustomObject>
    <fields>
        <fullName>Alolan_Picture_Url__c</fullName>
        <label>Alolan Picture Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Alolan_Type__c</fullName>
        <formula>TEXT(Alolan_Primary_Type__c) &amp; IF(NOT(ISBLANK(TEXT(Alolan_Secondary_Type__c))), &apos;/&apos; &amp; TEXT(Alolan_Secondary_Type__c), &apos;&apos;)</formula>
        <label>Alolan Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Galarian_Picture_Url__c</fullName>
        <description>URL to the picture depicting galarian form of the Pokemon</description>
        <label>Galarian Picture Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Galarian_Type__c</fullName>
        <formula>TEXT(Galarian_Primary_Type__c) &amp; IF(NOT(ISBLANK(TEXT(Galarian_Secondary_Type__c))), &apos;/&apos; &amp; TEXT(Galarian_Secondary_Type__c), &apos;&apos;)</formula>
        <label>Galarian Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picture_Url__c</fullName>
        <label>Picture Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(Primary_Type__c) &amp; IF(NOT(ISBLANK(TEXT(Secondary_Type__c))), &apos;/&apos; &amp; TEXT(Secondary_Type__c), &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PMHR_PokemonPictureController.cls
public class PMHR_PokemonPictureController {
    @AuraEnabled
    public static PokemonPicture getPokemonPicture(Id pokemonId) {
        Pokemon__c pokemon = getPokemonData(pokemonId);
        PokemonPicture result;
        if (pokemon.Variant__c == PMHR_Utilities.REGION_VARIANT_ALOLAN) {
            result = new PokemonPicture(pokemon.Form__r.Alolan_Picture_Url__c, pokemon.Form__r.Alolan_Type__c);
        } else if (pokemon.Variant__c == PMHR_Utilities.REGION_VARIANT_GALARIAN) {
            result = new PokemonPicture(pokemon.Form__r.Galarian_Picture_Url__c, pokemon.Form__r.Galarian_Type__c);
        } else {
            result = new PokemonPicture(pokemon.Form__r.Picture_Url__c, pokemon.Form__r.Type__c);
        }

        return result;
    }

    private static Pokemon__c getPokemonData(Id pokemonId) {
        return [
                SELECT Id, Variant__c,
                        Form__r.Picture_Url__c, Form__r.Type__c,
                        Form__r.Alolan_Picture_Url__c, Form__r.Alolan_Type__c,
                        Form__r.Galarian_Picture_Url__c, Form__r.Galarian_Type__c
                FROM Pokemon__c
                WHERE Id = :pokemonId
                LIMIT 1];
    }

    private Class PokemonPicture {
        @AuraEnabled public String pictureUrl { get; private set; }
        @AuraEnabled public String pokemonType { get; private set; }

        public PokemonPicture (String pictureUrl, String pokemonType) {
            this.pictureUrl = pictureUrl;
            this.pokemonType = pokemonType;
        }
    }
}