src/objects/Pokemon__c.object
<CustomObject>
    <fields>
        <fullName>Caught_Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Caught Form</label>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons (Caught)</relationshipLabel>
        <relationshipName>Caught_Pokemons</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
        <label>Form</label>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Pokemon__c.object
    <fields>
        <fullName>Region_Specific_Variant__c</fullName>
        <label>Region Specific Variant</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>

src/objects/Pokemon_Data__c.object
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Pokemon_Data__c.object
    <fields>
        <fullName>Region_Specific_Variant__c</fullName>
        <label>Region Specific Variant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>

temp/objects/Pokemon_Data__c.object
    <fields>
        <fullName>Variant_Of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Variant Of</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Pokemon_Data__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Additional Variants</relationshipLabel>
        <relationshipName>Additional_Variants</relationshipName>
        <type>Lookup</type>
    </fields>

src/globalValueSets/Region_Specific_Pokemon_Variants.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Region Specific Pokemon Variants</masterLabel>
</GlobalValueSet>

src/classes/PMHR_TriggerHandlerPokemon_Helper.cls
public class PMHR_TriggerHandlerPokemon_Helper {
    public static List<Pokemon_Data__c> getRelatedPokemonForms(Set<Id> pokemonDataIds) {
        return PMHR_PokemonDataQueryService.getPokemonFormsByIds(pokemonDataIds);
    }

    public static void copyCaughtFormToForm(Pokemon__c pokemon) {
        if (pokemon.Form__c == null) {
            pokemon = new PMHR_PokemonBuilder(pokemon)
                    .setForm(pokemon.Caught_Form__c)
                    .build();
        }
    }

    public static void validateRegionSpecificVariant(Pokemon__c pokemon, Map<Id, Pokemon_Data__c> relatedPokemonForms) {
        Pokemon_Data__c relatedForm = relatedPokemonForms.get(pokemon.Form__c);
        if (!isRegionSpecificVariantAvailable(relatedForm.Additional_Variants__r, pokemon.Region_Specific_Variant__c)) {
            pokemon.Region_Specific_Variant__c.addError(String.format(System.Label.PMHR_Error_Forbidden_Form_Variant, new List<String>{pokemon.Region_Specific_Variant__c}));
        }
    }

    private static Boolean isRegionSpecificVariantAvailable(List<Pokemon_Data__c> additionalForms, String regionSpecificVariant) {
        if (regionSpecificVariant == PMHR_Utilities.REGION_VARIANT_STANDARD) {
            return true;
        }
        for (Pokemon_Data__c additionalForm : additionalForms) {
            if (additionalForm.Region_Specific_Variant__c == regionSpecificVariant) {
                return true;
            }
        }
        return false;
    }
}