src/objects/Pokemon_Data__c.object
<CustomObject>
    <fields>
        <fullName>Pokedex_Number__c</fullName>
        <defaultValue>TEXT(000)</defaultValue>
        <externalId>true</externalId>
        <label>Pokedex Number</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Pokemon_Data__c.object
    <fields>
        <fullName>Region_Specific_Variant__c</fullName>
        <label>Region Specific Variant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>

temp/objects/Pokemon_Data__c.object
    <fields>
        <fullName>Variant_Name__c</fullName>
        <formula>TEXT(Region_Specific_Variant__c) &amp; &apos; &apos; &amp; Variant_Of__r.Name</formula>
        <label>Variant Name</label>
        <type>Text</type>
    </fields>

temp/objects/Pokemon_Data__c.object
    <fields>
        <fullName>Variant_Of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Variant Of</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Pokemon_Data__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Additional Variants</relationshipLabel>
        <relationshipName>Additional_Variants</relationshipName>
        <type>Lookup</type>
    </fields>

src/globalValueSets/Region_Specific_Pokemon_Variants.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Region Specific Pokemon Variants</masterLabel>
</GlobalValueSet>

src/classes/PMHR_TriggerHandlerPokemonData_Helper.cls
public with sharing class PMHR_TriggerHandlerPokemonData_Helper {

    public static Set<Id> getPokemonDataIds(List<Pokemon_Data__c> pokemonData, SObjectField field) {
        return PMHR_Utilities.fetchSObjectListToIdSet(pokemonData, field, false);
    }

    public static Set<String> getPokemonPokedexNumbers(List<Pokemon_Data__c> pokemonData) {
        return PMHR_Utilities.fetchSObjectListToStringSet(pokemonData, Pokemon_Data__c.Pokedex_Number__c, false);
    }

    public static List<Pokemon_Data__c> getExistingPokemonData(Set<Id> pokemonDataIds, Set<String> pokedexNumbers) {
        return PMHR_PokemonDataQueryService.getPokemonFormByIdsOrPokedexNumbers(pokemonDataIds, pokedexNumbers);
    }

    public static List<Pokemon_Data__c> getExistingPokemonAdditionalVariants(Set<Id> pokemonDataIds) {
        return PMHR_PokemonDataQueryService.getAdditionalVariantByFormIds(pokemonDataIds);
    }

    public static void validateDuplicatePokedexNumber(Pokemon_Data__c pokemonForm, Set<String> existingPokedexNumbers) {
        if (String.isNotBlank(pokemonForm.Pokedex_Number__c) && existingPokedexNumbers.contains(pokemonForm.Pokedex_Number__c)) {
            pokemonForm.Pokedex_Number__c.addError(System.Label.PMHR_Duplicate_Value_Error);
        }
    }

    public static void validateDuplicateRegionSpecificVariant(Pokemon_Data__c additionalVariant, Map<Id, Pokemon_Data__c> existingPokemonForms) {
        if (String.isNotBlank(additionalVariant.Region_Specific_Variant__c)) {
            Pokemon_Data__c pokemonForm = existingPokemonForms.get(additionalVariant.Variant_Of__c);
            for (Pokemon_Data__c existingAdditionalVariant : pokemonForm.Additional_Variants__r) {
                if (existingAdditionalVariant.Region_Specific_Variant__c == additionalVariant.Region_Specific_Variant__c
                        && existingAdditionalVariant.Id != additionalVariant.Id) {
                    additionalVariant.Region_Specific_Variant__c.addError(System.Label.PMHR_Duplicate_Value_Error);
                }
            }
        }
    }

    public static void copyVariantNameToForm(Pokemon_Data__c additionalVariant) {
        additionalVariant = new PMHR_PokemonAdditionalVariantBuilder(additionalVariant)
                .setForm(additionalVariant.Variant_Name__c)
                .build();
    }
}