force-app/main/default/objects/PMHR_Hero__c/PMHR_Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Nuzlocke__c/PMHR_Nuzlocke__c.object-meta.xml
<CustomObject>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Pokemon__c/PMHR_Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Pokemon__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
    <label>Form</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Pokemons</relationshipLabel>
    <relationshipName>Pokemons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/PMHR_PokemonData__c.object-meta.xml
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PictureUrl__c.field-meta.xml
<CustomField>
    <fullName>PictureUrl__c</fullName>
    <label>Picture Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(PrimaryType__c) &amp; IF(NOT(ISBLANK(TEXT(SecondaryType__c))), &apos;/&apos; &amp; TEXT(SecondaryType__c), &apos;&apos;)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/PMHR_PokemonRegionalVariant.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Pokemon Regional Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/lwcControllers/PMHR_PokemonPictureController_Test.cls
@IsTest
private class PMHR_PokemonPictureController_Test {
    private static final String STANDARD_PICTURE_URL = 'www.test.com.pl';
    private static final String ADDITIONAL_PICTURE_URL = 'www.test.additional.com.pl';

    @TestSetup static void setup() {
        PMHR_Hero__c hero = new PMHR_HeroBuilder()
                .save();
        PMHR_Nuzlocke__c nuzlocke = new PMHR_NuzlockeBuilder()
                .setHero(hero.Id)
                .save();
        PMHR_PokemonData__c pokemonData = new PMHR_PokemonFormBuilder()
                .setPictureUrl(STANDARD_PICTURE_URL)
                .save();
        PMHR_PokemonData__c additionalForm = new PMHR_PokemonAdditionalVariantBuilder()
                .setVariantOf(pokemonData.Id)
                .setPictureUrl(ADDITIONAL_PICTURE_URL)
                .setPrimaryType(PMHR_PokemonDataBuilder.TYPE_DARK)
                .save();
        PMHR_Pokemon__c pokemon = new PMHR_PokemonBuilder()
                .setCaughtForm(pokemonData.Id)
                .setNuzlocke(nuzlocke.Id)
                .save();
    }

    static testMethod void shouldGetPokemonFormUrl() {
        //given
        PMHR_Pokemon__c pokemon = [SELECT Id, Form__c, RegionalVariant__c, Form__r.PictureUrl__c, Form__r.Type__c FROM PMHR_Pokemon__c LIMIT 1];

        //when
        PMHR_PokemonPictureController.PokemonPicture pictureData = PMHR_PokemonPictureController.getPokemonPicture(pokemon.Id);

        //then
        System.assertEquals(pokemon.Form__r.PictureUrl__c, pictureData.pictureUrl);
        System.assertEquals(pokemon.Form__r.Type__c, pictureData.pokemonType);
    }

    static testMethod void shouldGetPokemonAdditinalVariantUrl() {
        //given
        PMHR_Pokemon__c pokemon = [SELECT Id, Form__c, RegionalVariant__c, Form__r.PictureUrl__c, Form__r.Type__c FROM PMHR_Pokemon__c LIMIT 1];
        pokemon = new PMHR_PokemonBuilder(pokemon)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .save();

        //when
        PMHR_PokemonPictureController.PokemonPicture pictureData = PMHR_PokemonPictureController.getPokemonPicture(pokemon.Id);

        //then
        System.assertNotEquals(pokemon.Form__r.PictureUrl__c, pictureData.pictureUrl);
        System.assertNotEquals(pokemon.Form__r.Type__c, pictureData.pokemonType);
        System.assertEquals(ADDITIONAL_PICTURE_URL, pictureData.pictureUrl);
        System.assertEquals(PMHR_PokemonDataBuilder.TYPE_DARK, pictureData.pokemonType);
    }
}