force-app/main/default/objects/PMHR_Hero__c/PMHR_Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Nuzlocke__c/PMHR_Nuzlocke__c.object-meta.xml
<CustomObject>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Pokemon__c/PMHR_Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Pokemon__c/fields/CaughtForm__c.field-meta.xml
<CustomField>
    <fullName>CaughtForm__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Caught Form</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Pokemons (Caught)</relationshipLabel>
    <relationshipName>CaughtPokemons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
    <label>Form</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Pokemons</relationshipLabel>
    <relationshipName>Pokemons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/PMHR_PokemonData__c.object-meta.xml
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_PokemonData__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abra</fullName>
            </value>
            <value>
                <fullName>Absol</fullName>
            </value>
            <value>
                <fullName>Aerodactyl</fullName>
            </value>
            <value>
                <fullName>Aipom</fullName>
            </value>
            <value>
                <fullName>Alomomola</fullName>
            </value>
            <value>
                <fullName>Amaura</fullName>
            </value>
            <value>
                <fullName>Anorith</fullName>
            </value>
            <value>
                <fullName>Applin</fullName>
            </value>
            <value>
                <fullName>Arceus</fullName>
            </value>
            <value>
                <fullName>Archen</fullName>
            </value>
            <value>
                <fullName>Arctovish</fullName>
            </value>
            <value>
                <fullName>Arctozolt</fullName>
            </value>
            <value>
                <fullName>Aron</fullName>
            </value>
            <value>
                <fullName>Arrokuda</fullName>
            </value>
            <value>
                <fullName>Articuno</fullName>
            </value>
            <value>
                <fullName>Audino</fullName>
            </value>
            <value>
                <fullName>Axew</fullName>
            </value>
            <value>
                <fullName>Azelf</fullName>
            </value>
            <value>
                <fullName>Azurill</fullName>
            </value>
            <value>
                <fullName>Bagon</fullName>
            </value>
            <value>
                <fullName>Baltoy</fullName>
            </value>
            <value>
                <fullName>Barboach</fullName>
            </value>
            <value>
                <fullName>Basculin</fullName>
            </value>
            <value>
                <fullName>Beldum</fullName>
            </value>
            <value>
                <fullName>Bellsprout</fullName>
            </value>
            <value>
                <fullName>Bergmite</fullName>
            </value>
            <value>
                <fullName>Bidoof</fullName>
            </value>
            <value>
                <fullName>Binacle</fullName>
            </value>
            <value>
                <fullName>Blacephalon</fullName>
            </value>
            <value>
                <fullName>Blipbug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/FamilyStage__c.field-meta.xml
<CustomField>
    <fullName>FamilyStage__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Family Stage</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/recordTypes/Form.recordType-meta.xml
<RecordType>
    <fullName>Form</fullName>
    <active>true</active>
    <description>Standard form of the Pokemon species</description>
    <label>Form</label>
</RecordType>

force-app/main/default/globalValueSets/PMHR_PokemonRegionalVariant.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Pokemon Regional Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/triggerHandlers/PMHR_TriggerHandlerPokemon_Test.cls
@IsTest
private class PMHR_TriggerHandlerPokemon_Test {
    @TestSetup static void setup() {
        PMHR_Hero__c hero = new PMHR_HeroBuilder()
                .save();

        PMHR_Nuzlocke__c nuzlocke = new PMHR_NuzlockeBuilder()
                .setHero(hero.Id)
                .save();

        List<PMHR_PokemonData__c> pokemonData = new List<PMHR_PokemonData__c>();
        for (Integer i = 1; i < 3; i++) {
            pokemonData.add(new PMHR_PokemonFormBuilder()
                    .setPokedexNumber('00' + i)
                    .setForm('Testor v' + i)
                    .setPrimaryType(PMHR_PokemonDataBuilder.TYPE_NORMAL)
                    .setFamily('Testor')
                    .setFamilyStage(i)
                    .build()
            );
        }
        pokemonData.add(new PMHR_PokemonFormBuilder()
                .setPokedexNumber('003')
                .setForm('Alestor')
                .setPrimaryType(PMHR_PokemonDataBuilder.TYPE_DARK)
                .setFamily('Alestor')
                .setFamilyStage(1)
                .build());
        insert pokemonData;
    }

    static testMethod void shouldCopyCaughtFormToFormOnInsert() {
        //given
        PMHR_PokemonData__c form = [SELECT Id FROM PMHR_PokemonData__c LIMIT 1];
        PMHR_Nuzlocke__c nuzlocke = [SELECT Id FROM PMHR_Nuzlocke__c LIMIT 1];

        //when
        Test.startTest();
        PMHR_Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                .setCaughtForm(form.Id)
                .setNuzlocke(nuzlocke.Id)
                .save();
        Test.stopTest();

        //then
        newPokemon = [SELECT CaughtForm__c, Form__c FROM PMHR_Pokemon__c LIMIT 1];
        System.assertEquals(newPokemon.CaughtForm__c, newPokemon.Form__c);
    }

    static testMethod void shouldNotCopyCaughtFormToFormOnInsert_formProvided() {
        //given
        List<PMHR_PokemonData__c> forms = [SELECT Id, FamilyStage__c FROM PMHR_PokemonData__c WHERE Family__c = 'Testor' LIMIT 2];
        PMHR_Nuzlocke__c nuzlocke = [SELECT Id FROM PMHR_Nuzlocke__c LIMIT 1];

        PMHR_PokemonData__c firstStageForm;
        PMHR_PokemonData__c secondStageForm;

        for (PMHR_PokemonData__c form : forms) {
            if (form.FamilyStage__c == 1) {
                firstStageForm = form;
            } else {
                secondStageForm = form;
            }
        }

        //when
        Test.startTest();
        PMHR_Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                .setCaughtForm(firstStageForm.Id)
                .setForm(secondStageForm.Id)
                .setNuzlocke(nuzlocke.Id)
                .save();
        Test.stopTest();

        //then
        newPokemon = [SELECT CaughtForm__c, Form__c FROM PMHR_Pokemon__c LIMIT 1];
        System.assertNotEquals(newPokemon.CaughtForm__c, newPokemon.Form__c);
        System.assertEquals(newPokemon.CaughtForm__c, firstStageForm.Id);
        System.assertEquals(newPokemon.Form__c, secondStageForm.Id);
    }

    static testMethod void shouldNotInsertPokemon_nuzlockeFinished() {
        //given
        PMHR_PokemonData__c form = [SELECT Id FROM PMHR_PokemonData__c LIMIT 1];
        PMHR_Nuzlocke__c nuzlocke = [SELECT Id FROM PMHR_Nuzlocke__c LIMIT 1];
        nuzlocke = new PMHR_NuzlockeBuilder(nuzlocke)
                .setEndDate(Date.today())
                .setEndStatus(PMHR_NuzlockeBuilder.END_STATUS_FAILED)
                .save();

        Boolean errorOccurred = false;

        //when
        Test.startTest();
        try {
            PMHR_Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                    .setNuzlocke(nuzlocke.Id)
                    .setCaughtForm(form.Id)
                    .save();
        } catch (DmlException ex) {
            errorOccurred = true;
        }
        Test.stopTest();

        //then
        System.assert(errorOccurred);
        System.assertEquals(0, [SELECT Count() FROM PMHR_Pokemon__c]);
    }

    static testMethod void shouldInsertPokemon_allowedVariant() {
        //given
        PMHR_PokemonData__c form = [SELECT Id FROM PMHR_PokemonData__c LIMIT 1];
        PMHR_Nuzlocke__c nuzlocke = [SELECT Id FROM PMHR_Nuzlocke__c LIMIT 1];
        PMHR_PokemonData__c additionalVariant = new PMHR_PokemonAdditionalVariantBuilder()
                .setVariantOf(form.Id)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .save();

        //when
        Test.startTest();
        PMHR_Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                .setNuzlocke(nuzlocke.Id)
                .setCaughtForm(form.Id)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .save();
        Test.stopTest();

        //then
        System.assertEquals(1, [SELECT Count() FROM PMHR_Pokemon__c]);
    }

    static testMethod void shouldNotInsertPokemon_forbiddenVariant() {
        //given
        PMHR_PokemonData__c form = [SELECT Id FROM PMHR_PokemonData__c LIMIT 1];
        PMHR_Nuzlocke__c nuzlocke = [SELECT Id FROM PMHR_Nuzlocke__c LIMIT 1];

        Boolean errorOccurred = false;

        //when
        Test.startTest();
        try {
            PMHR_Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                    .setNuzlocke(nuzlocke.Id)
                    .setCaughtForm(form.Id)
                    .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                    .save();
        } catch (DmlException ex) {
            errorOccurred = true;
        }
        Test.stopTest();

        //then
        System.assert(errorOccurred);
        System.assertEquals(0, [SELECT Count() FROM PMHR_Pokemon__c]);
    }

    static testMethod void shouldUpdatePokemon_allowedVariant() {
        //given
        PMHR_PokemonData__c form = [SELECT Id FROM PMHR_PokemonData__c LIMIT 1];
        PMHR_Nuzlocke__c nuzlocke = [SELECT Id FROM PMHR_Nuzlocke__c LIMIT 1];
        PMHR_PokemonData__c additionalVariant = new PMHR_PokemonAdditionalVariantBuilder()
                .setVariantOf(form.Id)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .save();
        PMHR_Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                .setNuzlocke(nuzlocke.Id)
                .setCaughtForm(form.Id)
                .save();

        //when
        Test.startTest();
        newPokemon = new PMHR_PokemonBuilder(newPokemon)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .save();
        Test.stopTest();

        //then
        newPokemon = PMHR_PokemonQueryService.getPokemonById(newPokemon.Id);
        System.assertEquals(PMHR_Utilities.REGION_VARIANT_ALOLAN, newPokemon.RegionalVariant__c);
    }

    static testMethod void shouldNotUpdatePokemon_forbiddenVariant() {
        //given
        PMHR_PokemonData__c form = [SELECT Id FROM PMHR_PokemonData__c LIMIT 1];
        PMHR_Nuzlocke__c nuzlocke = [SELECT Id FROM PMHR_Nuzlocke__c LIMIT 1];
        PMHR_Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                .setNuzlocke(nuzlocke.Id)
                .setCaughtForm(form.Id)
                .save();

        Boolean errorOccurred = false;

        //when
        Test.startTest();
        try {
            newPokemon = new PMHR_PokemonBuilder(newPokemon)
                    .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                    .save();
        } catch (DmlException ex) {
            errorOccurred = true;
        }
        Test.stopTest();

        //then
        newPokemon = PMHR_PokemonQueryService.getPokemonById(newPokemon.Id);
        System.assertNotEquals(PMHR_Utilities.REGION_VARIANT_ALOLAN, newPokemon.RegionalVariant__c);
    }
}