force-app/main/default/objects/PMHR_FinalTeamMember__c/PMHR_FinalTeamMember__c.object-meta.xml
<CustomObject>
    <label>Final Team Member</label>
    <nameField>
        <displayFormat>FTM-{000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Ability__c.field-meta.xml
<CustomField>
    <fullName>Ability__c</fullName>
    <label>Ability</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/FinalTeam__c.field-meta.xml
<CustomField>
    <fullName>FinalTeam__c</fullName>
    <label>Final Team</label>
    <referenceTo>PMHR_FinalTeam__c</referenceTo>
    <relationshipLabel>Final Team Members</relationshipLabel>
    <relationshipName>FinalTeamMembers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/HeldItem__c.field-meta.xml
<CustomField>
    <fullName>HeldItem__c</fullName>
    <label>Held Item</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokemon</label>
    <referenceTo>PMHR_Pokemon__c</referenceTo>
    <relationshipLabel>Final Team Members</relationshipLabel>
    <relationshipName>FinalTeamMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

temp/objects/Pokemon__c.object
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/objectBuilders/sObjectBuilders/PMHR_FinalTeamMemberBuilder.cls
public with sharing class PMHR_FinalTeamMemberBuilder {
    private static final String MOVE_API_NAME_FORMAT = 'Move{0}__c';
    private PMHR_FinalTeamMember__c record;

    private PMHR_FinalTeamMember__c defaultData() {
        return new PMHR_FinalTeamMember__c();
    }

    public PMHR_FinalTeamMemberBuilder() {
        this.record = this.defaultData();
    }

    public PMHR_FinalTeamMemberBuilder reset() {
        this.record = this.defaultData();
        return this;
    }

    public PMHR_FinalTeamMember__c build() {
        PMHR_FinalTeamMember__c record = this.record;
        this.reset();
        return record;
    }

    public PMHR_FinalTeamMember__c save() {
        PMHR_FinalTeamMember__c record = this.build();
        upsert record;
        return record;
    }

    public PMHR_FinalTeamMemberBuilder setFinalTeam(Id finalTeam) {
        this.record.FinalTeam__c = finalTeam;
        return this;
    }

    public PMHR_FinalTeamMemberBuilder setPokemon(Id pokemonId) {
        this.record.Pokemon__c = pokemonId;
        return this;
    }

    public PMHR_FinalTeamMemberBuilder setAbility(String ability) {
        this.record.Ability__c = ability;
        return this;
    }

    public PMHR_FinalTeamMemberBuilder setHeldItem(String heldItem) {
        this.record.HeldItem__c = heldItem;
        return this;
    }

    public PMHR_FinalTeamMemberBuilder setLevel(Integer level) {
        this.record.Level__c = Decimal.valueOf(level);
        return this;
    }

    public PMHR_FinalTeamMemberBuilder setMoves(Map<Integer, String> moves) {
        if (moves == null || moves.size() > 4) {
            throw new InvalidNumberOfMovesException();
        }
        for (Integer moveNumber : moves.keySet()) {
            if (moveNumber <= 0 || moveNumber > 4) {
                throw new InvalidMoveNumberException();
            }
            this.record.put(String.format(MOVE_API_NAME_FORMAT, new List<String>{String.valueOf(moveNumber)}), moves.get(moveNumber));
        }
        return this;
    }

    public PMHR_FinalTeamMemberBuilder setNature(String nature) {
        this.record.Nature__c = nature;
        return this;
    }

    public class InvalidNumberOfMovesException extends Exception{}
    public class InvalidMoveNumberException extends Exception {}
}