force-app/main/default/objects/PMHR_FinalTeamMember__c/PMHR_FinalTeamMember__c.object-meta.xml
<CustomObject>
    <label>Final Team Member</label>
    <nameField>
        <displayFormat>FTM-{000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Ability__c.field-meta.xml
<CustomField>
    <fullName>Ability__c</fullName>
    <label>Ability</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/FinalTeam__c.field-meta.xml
<CustomField>
    <fullName>FinalTeam__c</fullName>
    <label>Final Team</label>
    <referenceTo>PMHR_FinalTeam__c</referenceTo>
    <relationshipLabel>Final Team Members</relationshipLabel>
    <relationshipName>FinalTeamMembers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/HeldItem__c.field-meta.xml
<CustomField>
    <fullName>HeldItem__c</fullName>
    <label>Held Item</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Move1__c.field-meta.xml
<CustomField>
    <fullName>Move1__c</fullName>
    <label>Move 1</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Move2__c.field-meta.xml
<CustomField>
    <fullName>Move2__c</fullName>
    <label>Move 2</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Move3__c.field-meta.xml
<CustomField>
    <fullName>Move3__c</fullName>
    <label>Move 3</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Move4__c.field-meta.xml
<CustomField>
    <fullName>Move4__c</fullName>
    <label>Move 4</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokemon</label>
    <referenceTo>PMHR_Pokemon__c</referenceTo>
    <relationshipLabel>Final Team Members</relationshipLabel>
    <relationshipName>FinalTeamMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>Pokemon__r.Form__r.Type__c</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

temp/objects/Pokemon__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
        <label>Form</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Pokemon_Data__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/services/PMHR_FinalTeamMemberQueryService.cls
public with sharing class PMHR_FinalTeamMemberQueryService {
    public static PMHR_FinalTeamMember__c getFinalTeamMemberById(Id finalTeamMemberId) {
        return [
                SELECT Id, Form__c, Ability__c, Nature__c, HeldItem__c, FinalTeam__c, Pokemon__c, Level__c, Type__c,
                        Move1__c, Move2__c, Move3__c, Move4__c
                FROM PMHR_FinalTeamMember__c
                WHERE Id = :finalTeamMemberId
                LIMIT 1
        ];
    }
}