temp/objects/Final_Team__c.object
<CustomObject>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Final Teams</relationshipLabel>
        <relationshipName>Final_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Nuzlocke__c.object
<CustomObject>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PMHR_NewFinalTeamButtonController.cls
public class PMHR_NewFinalTeamButtonController {

    @AuraEnabled
    public static void createFinalTeam(String nuzlockeId, String finalTeamName) {
        try {
            Final_Team__c finalTeam = new Final_Team__c(Nuzlocke__c = nuzlockeId, Name = finalTeamName);
            insert finalTeam;
        } catch (DmlException ex) {
            throw new AuraHandledException(ex.getDmlMessage(0));
        }
    }
}