temp/objects/Final_Team__c.object
<CustomObject>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Final Teams</relationshipLabel>
        <relationshipName>Final_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Final_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Final_Team__c</fullName>
        <label>Final Team</label>
        <referenceTo>Final_Team__c</referenceTo>
        <relationshipLabel>Final Team Members</relationshipLabel>
        <relationshipName>Final_Team_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pokemon__c</fullName>
        <label>Pokemon</label>
        <referenceTo>Pokemon__c</referenceTo>
        <relationshipLabel>Final Team Members</relationshipLabel>
        <relationshipName>Final_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Final Team Member</label>
    <nameField>
        <displayFormat>FTM-{000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Hero__c.object
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Nuzlocke__c.object
<CustomObject>
    <fields>
        <fullName>Hero__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Hero</label>
        <referenceTo>Hero__c</referenceTo>
        <relationshipLabel>Nuzlockes</relationshipLabel>
        <relationshipName>Nuzlockes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Pokemon__c.object
<CustomObject>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Pokemon_Data__c.object
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PMHR_FinalTeamListController_Test.cls
@IsTest
private class PMHR_FinalTeamListController_Test {
    @TestSetup static void setup() {
        Integer numberOfPokemons = 6;
        List<String> regionSpecificVariants = PMHR_Utilities.getPokemonRegionalVariantsValues();

        Hero__c hero = new PMHR_HeroBuilder()
                .save();

        Nuzlocke__c nuzlocke = new PMHR_NuzlockeBuilder()
                .setHero(hero.Id)
                .save();

        List<Pokemon_Data__c> pokemonData = new List<Pokemon_Data__c>();
        PMHR_PokemonFormBuilder pokemonFormBuilder = new PMHR_PokemonFormBuilder();
        for (Integer i = 0; i < numberOfPokemons; i++) {
            pokemonData.add(pokemonFormBuilder
                    .setPokedexNumber('00' + (i + 1))
                    .setForm('Testor v' + i)
                    .setPrimaryType(PMHR_PokemonDataBuilder.TYPE_NORMAL)
                    .setFamily('Testor v' + i)
                    .setFamilyStage(1)
                    .build()
            );
        }
        insert pokemonData;

        List<Pokemon__c> pokemons = new List<Pokemon__c>();
        PMHR_PokemonBuilder pokemonBuilder = new PMHR_PokemonBuilder();
        for (Integer i = 0; i < numberOfPokemons; i++) {
            pokemons.add(pokemonBuilder
                    .setName('Testinho ' + i)
                    .setGender(PMHR_Utilities.GENDER_MALE)
                    .setCaughtForm(pokemonData.get(i).Id)
                    .setNuzlocke(nuzlocke.Id)
                    .build()
            );
        }
        insert pokemons;

        Final_Team__c finalTeam = new PMHR_FinalTeamBuilder()
                .setNuzlocke(nuzlocke.Id)
                .save();

        List<Final_Team_Member__c> finalTeamMembers = new List<Final_Team_Member__c>();
        for (Integer i = 0; i < numberOfPokemons; i++) {
            finalTeamMembers.add(new PMHR_FinalTeamMemberBuilder()
                    .setFinalTeam(finalTeam.Id)
                    .setPokemon(pokemons.get(i).Id)
                    .build()
            );
        }
        insert finalTeamMembers;
    }

    static testMethod void shouldGetFinalTeamInfo() {
        //given
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        Final_Team__c finalTeam = [SELECT Id, Name FROM Final_Team__c LIMIT 1];

        //when
        Test.startTest();
        List<PMHR_FinalTeamListControllerHelper.FinalTeam> finalTeamWrappers = PMHR_FinalTeamListController.getFinalTeamInfo(nuzlocke.Id);
        Test.stopTest();

        //then
        System.assert(!finalTeamWrappers.isEmpty());
        PMHR_FinalTeamListControllerHelper.FinalTeam finalTeamWrapper = finalTeamWrappers.get(0);
        System.assertEquals(finalTeam.Id, finalTeamWrapper.id);
        System.assertEquals(finalTeam.Name, finalTeamWrapper.name);
        System.assertEquals(6, finalTeamWrapper.members.size());
    }

    static testMethod void shouldNotGetFinalTeamInfo_noFinalTeams() {
        //given
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        delete [SELECT Id FROM Final_Team__c];

        //when
        Test.startTest();
        List<PMHR_FinalTeamListControllerHelper.FinalTeam> finalTeamWrappers = PMHR_FinalTeamListController.getFinalTeamInfo(nuzlocke.Id);
        Test.stopTest();

        //then
        System.assert(finalTeamWrappers.isEmpty());
    }
}