temp/objects/Final_Team__c.object
<CustomObject>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Final Teams</relationshipLabel>
        <relationshipName>Final_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Hero__c.object
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Nuzlocke__c.object
<CustomObject>
    <fields>
        <fullName>End_Status__c</fullName>
        <label>End Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hero__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Hero</label>
        <referenceTo>Hero__c</referenceTo>
        <relationshipLabel>Nuzlockes</relationshipLabel>
        <relationshipName>Nuzlockes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Finished__c</fullName>
        <description>Indicate if Nuzlocke is finished</description>
        <formula>AND(
 NOT(ISBLANK(End_Date__c)),
 NOT(ISBLANK(TEXT(End_Status__c)))
)</formula>
        <label>Is Finished</label>
        <type>Checkbox</type>
    </fields>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PMHR_TriggerHandlerNuzlocke_Test.cls
@IsTest
private class PMHR_TriggerHandlerNuzlocke_Test {
    @TestSetup static void setup() {
        Hero__c hero = new PMHR_HeroBuilder()
                .save();
        Nuzlocke__c nuzlocke = new PMHR_NuzlockeBuilder()
                .setHero(hero.Id)
                .save();
    }

    static testMethod void shouldNotFinishNuzlocke_WithStatusSuccess() {
        //given
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        Boolean errorOccurred = false;

        //when
        Test.startTest();
        try {
            nuzlocke = new PMHR_NuzlockeBuilder(nuzlocke)
                    .setEndDate(Date.today())
                    .setEndStatus(PMHR_NuzlockeBuilder.END_STATUS_SUCCESS)
                    .save();
        } catch (Exception ex) {
            errorOccurred = true;
        }
        Test.stopTest();

        //then
        nuzlocke = PMHR_NuzlockeQueryService.getNuzlockeById(nuzlocke.Id);
        System.assert(!nuzlocke.Is_Finished__c);
        System.assert(errorOccurred);
    }

    static testMethod void shouldFinishNuzlocke_WithStatusFailure() {
        //given
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        Boolean errorOccurred = false;

        //when
        Test.startTest();
        try {
            nuzlocke = new PMHR_NuzlockeBuilder(nuzlocke)
                    .setEndDate(Date.today())
                    .setEndStatus(PMHR_NuzlockeBuilder.END_STATUS_FAILED)
                    .save();
        } catch (Exception ex) {
            errorOccurred = true;
        }
        Test.stopTest();

        //then
        nuzlocke = PMHR_NuzlockeQueryService.getNuzlockeById(nuzlocke.Id);
        System.assert(nuzlocke.Is_Finished__c);
        System.assertEquals(nuzlocke.End_Status__c, PMHR_NuzlockeBuilder.END_STATUS_FAILED);
        System.assert(!errorOccurred);
    }

    static testMethod void shouldFinishNuzlocke_WithStatusSuccess() {
        //given
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        Boolean errorOccurred = false;

        //when
        Test.startTest();
        try {
            Final_Team__c newFinalTeam = new PMHR_FinalTeamBuilder()
                    .setNuzlocke(nuzlocke.Id)
                    .save();
        } catch (Exception ex) {
            errorOccurred = true;
        }
        Test.stopTest();

        //then
        nuzlocke = [SELECT Id, Is_Finished__c, End_Status__c FROM Nuzlocke__c WHERE Id = :nuzlocke.Id];
        System.assert(nuzlocke.Is_Finished__c);
        System.assertEquals(PMHR_NuzlockeBuilder.END_STATUS_SUCCESS, nuzlocke.End_Status__c);
        System.assert(!errorOccurred);
    }

    static testMethod void shouldDeleteNuzlockeRelatedFinalTeam() {
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        Final_Team__c newFinalTeam = new PMHR_FinalTeamBuilder()
                .setNuzlocke(nuzlocke.Id)
                .save();
        System.assertEquals(1, [SELECT Count() FROM Nuzlocke__c]);
        System.assertEquals(1, [SELECT Count() FROM Final_Team__c]);

        //when
        Test.startTest();
        delete nuzlocke;
        Test.stopTest();

        //then
        System.assertEquals(0, [SELECT Count() FROM Nuzlocke__c]);
        System.assertEquals(0, [SELECT Count() FROM Final_Team__c]);
    }
}