temp/objects/Final_Team__c.object
<CustomObject>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Final Teams</relationshipLabel>
        <relationshipName>Final_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Hero__c.object
<CustomObject>
    <fields>
        <fullName>Game_Version__c</fullName>
        <label>Game Version</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pokemon_Game_Versions</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rival_Name__c</fullName>
        <label>Rival Name</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Nuzlocke__c.object
<CustomObject>
    <fields>
        <fullName>Allowed_Catching_Methods_Per_Area__c</fullName>
        <label>Allowed Catching Methods / Area</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Breeding (1)</fullName>
                </value>
                <value>
                    <fullName>Breeding (Any)</fullName>
                </value>
                <value>
                    <fullName>Breeding (One/Parent)</fullName>
                </value>
                <value>
                    <fullName>Breeding (One/Type)</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Fossil (1)</fullName>
                </value>
                <value>
                    <fullName>Fossil (Any)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (1)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (2)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (3)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (4)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (Any)</fullName>
                </value>
                <value>
                    <fullName>Headbutt</fullName>
                </value>
                <value>
                    <fullName>Land</fullName>
                </value>
                <value>
                    <fullName>Land/Water</fullName>
                </value>
                <value>
                    <fullName>Trade</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Water/Headbutt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Status__c</fullName>
        <label>End Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Game_Version__c</fullName>
        <formula>TEXT(Hero__r.Game_Version__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Game Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hero__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Hero</label>
        <referenceTo>Hero__c</referenceTo>
        <relationshipLabel>Nuzlockes</relationshipLabel>
        <relationshipName>Nuzlockes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Finished__c</fullName>
        <description>Indicate if Nuzlocke is finished</description>
        <formula>AND(
 NOT(ISBLANK(End_Date__c)),
 NOT(ISBLANK(TEXT(End_Status__c)))
)</formula>
        <label>Is Finished</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legendaries_Rule__c</fullName>
        <label>Legendaries Rule</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Catch - no use</fullName>
                </value>
                <value>
                    <fullName>Catch - use</fullName>
                </value>
                <value>
                    <fullName>Kill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Multiple_Elite_Four_Fights__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if Nuzlocke run involves more than one Elite Four fights, thus assembling more than one final team</description>
        <inlineHelpText>Check, if Nuzlocke run involves more than one Elite Four fights, thus assembling more than one final team</inlineHelpText>
        <label>Multiple Elite Four Fights</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pokemons_Caught__c</fullName>
        <description>Number of caught Pokemons</description>
        <label>Pokemons Caught</label>
        <summaryForeignKey>Pokemon__c.Nuzlocke__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Pokemons_Deceased__c</fullName>
        <description>Number of Pokemons lost in battle</description>
        <label>Pokemons Deceased</label>
        <summaryFilterItems>
            <field>Pokemon__c.Death__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Pokemon__c.Nuzlocke__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Rival_Name__c</fullName>
        <formula>Hero__r.Rival_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rival Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Safari_Zone_Rule__c</fullName>
        <label>Safari Zone Rule</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Amount of areas/Safari</fullName>
                </value>
                <value>
                    <fullName>One/Area</fullName>
                </value>
                <value>
                    <fullName>One/Safari</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Pokemon_Game_Versions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Yellow</fullName>
    </customValue>
    <customValue>
        <fullName>Fire Red</fullName>
    </customValue>
    <customValue>
        <fullName>Leaf Green</fullName>
    </customValue>
    <customValue>
        <fullName>Gold</fullName>
    </customValue>
    <customValue>
        <fullName>Silver</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal</fullName>
    </customValue>
    <customValue>
        <fullName>Heart Gold</fullName>
    </customValue>
    <customValue>
        <fullName>Soul Silver</fullName>
    </customValue>
    <customValue>
        <fullName>Ruby</fullName>
    </customValue>
    <customValue>
        <fullName>Sapphire</fullName>
    </customValue>
    <customValue>
        <fullName>Emerald</fullName>
    </customValue>
    <customValue>
        <fullName>Omega Ruby</fullName>
    </customValue>
    <customValue>
        <fullName>Alpha Sapphire</fullName>
    </customValue>
    <customValue>
        <fullName>Diamond</fullName>
    </customValue>
    <customValue>
        <fullName>Pearl</fullName>
    </customValue>
    <customValue>
        <fullName>Platinum</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>Black 2</fullName>
    </customValue>
    <customValue>
        <fullName>White 2</fullName>
    </customValue>
    <customValue>
        <fullName>X</fullName>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
    </customValue>
    <customValue>
        <fullName>Sun</fullName>
    </customValue>
    <customValue>
        <fullName>Moon</fullName>
    </customValue>
    <customValue>
        <fullName>Ultra Sun</fullName>
    </customValue>
    <customValue>
        <fullName>Ultra Moon</fullName>
    </customValue>
    <customValue>
        <fullName>Let&apos;s GO Pikachu</fullName>
    </customValue>
    <masterLabel>Pokemon Game Versions</masterLabel>
</GlobalValueSet>

src/classes/PMHR_NuzlockeQueryService.cls
public with sharing class PMHR_NuzlockeQueryService {
    public static Nuzlocke__c getNuzlockeById(Id nuzlockeId) {
        return [
                SELECT Id, Name, Start_Date__c, End_Date__c, End_Status__c, Hero__c, Rival_Name__c,
                        Allowed_Catching_Methods_Per_Area__c, Legendaries_Rule__c, Safari_Zone_Rule__c,
                        Game_Version__c, Is_Finished__c, Multiple_Elite_Four_Fights__c, Pokemons_Caught__c, Pokemons_Deceased__c
                FROM Nuzlocke__c
                WHERE Id = :nuzlockeId
                LIMIT 1
        ];
    }

    public static List<Nuzlocke__c> getNuzlockesWithFinalTeamsByIds(Set<Id> nuzlockeIds) {
        return [
                SELECT Id, Name, Start_Date__c, End_Date__c, End_Status__c, Hero__c, Rival_Name__c,
                        Allowed_Catching_Methods_Per_Area__c, Legendaries_Rule__c, Safari_Zone_Rule__c,
                        Game_Version__c, Is_Finished__c, Multiple_Elite_Four_Fights__c, Pokemons_Caught__c, Pokemons_Deceased__c,
                    (SELECT Name FROM Final_Teams__r)
                FROM Nuzlocke__c
                WHERE Id IN :nuzlockeIds
        ];
    }

    public static Nuzlocke__c getNuzlockeWithFinalTeamsById(Id nuzlockeId) {
        return getNuzlockesWithFinalTeamsByIds(new Set<Id>{nuzlockeId}).get(0);
    }
}