temp/objects/Final_Team__c.object
<CustomObject>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Final Teams</relationshipLabel>
        <relationshipName>Final_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Hero__c.object
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Nuzlocke__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Status__c</fullName>
        <label>End Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hero__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Hero</label>
        <referenceTo>Hero__c</referenceTo>
        <relationshipLabel>Nuzlockes</relationshipLabel>
        <relationshipName>Nuzlockes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Finished__c</fullName>
        <description>Indicate if Nuzlocke is finished</description>
        <formula>AND(
 NOT(ISBLANK(End_Date__c)),
 NOT(ISBLANK(TEXT(End_Status__c)))
)</formula>
        <label>Is Finished</label>
        <type>Checkbox</type>
    </fields>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PMHR_TriggerHandlerNuzlocke_Test.cls
@IsTest
private class PMHR_TriggerHandlerNuzlocke_Test {
    @TestSetup static void setup() {
        Hero__c hero = PMHR_TestDataFactory.createHeroObject('Hero', 'Kanto');
        insert hero;
        insert PMHR_TestDataFactory.createNuzlockeObject('Test Nuzlocke', Date.today(), hero.Id);
    }

    static testMethod void shouldNotFinishNuzlocke_WithStatusSuccess() {
        //given
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        String errorMessage;

        //when
        Test.startTest();
        try {
            nuzlocke.End_Status__c = PMHR_Utilities.NUZLOCKE_END_STATUS_SUCCESS;
            nuzlocke.End_Date__c = Date.today();
            update nuzlocke;
        } catch (Exception ex) {
            errorMessage = ex.getMessage();
        }
        Test.stopTest();

        //then
        nuzlocke = [SELECT Id, Is_Finished__c FROM Nuzlocke__c WHERE Id = :nuzlocke.Id LIMIT 1];
        System.assert(!nuzlocke.Is_Finished__c);
        System.assert(!String.isEmpty(errorMessage));
        System.assert(errorMessage.contains(Label.Toast_Error_Nuzlocke_Finished_With_Success_Without_Final_Team));
    }

    static testMethod void shouldFinishNuzlocke_WithStatusFailure() {
        //given
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        String errorMessage;

        //when
        Test.startTest();
        try {
            nuzlocke.End_Status__c = PMHR_Utilities.NUZLOCKE_END_STATUS_FAILED;
            nuzlocke.End_Date__c = Date.today();
            update nuzlocke;
        } catch (Exception ex) {
            errorMessage = ex.getMessage();
        }
        Test.stopTest();

        //then
        nuzlocke = [SELECT Id, Is_Finished__c, End_Status__c FROM Nuzlocke__c WHERE Id = :nuzlocke.Id LIMIT 1];
        System.assert(nuzlocke.Is_Finished__c);
        System.assertEquals(nuzlocke.End_Status__c, PMHR_Utilities.NUZLOCKE_END_STATUS_FAILED);
        System.assert(String.isEmpty(errorMessage));
    }

    static testMethod void shouldFinishNuzlocke_WithStatusSuccess() {
        //given
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        String errorMessage;

        //when
        Test.startTest();
        try {
            Final_Team__c newFinalTeam = PMHR_TestDataFactory.createFinalTeamObject('New Final Team', nuzlocke.Id);
            insert newFinalTeam;
        } catch (Exception ex) {
            errorMessage = ex.getMessage();
        }
        Test.stopTest();

        //then
        nuzlocke = [SELECT Id, Is_Finished__c, End_Status__c FROM Nuzlocke__c WHERE Id = :nuzlocke.Id];
        System.assert(nuzlocke.Is_Finished__c);
        System.assertEquals(PMHR_Utilities.NUZLOCKE_END_STATUS_SUCCESS, nuzlocke.End_Status__c);
        System.assert(String.isEmpty(errorMessage));
    }

    static testMethod void shouldDeleteNuzlockeRelatedFinalTeam() {
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        Final_Team__c newFinalTeam = PMHR_TestDataFactory.createFinalTeamObject('New Final Team', nuzlocke.Id);
        insert newFinalTeam;
        System.assertEquals(1, [SELECT Count() FROM Nuzlocke__c]);
        System.assertEquals(1, [SELECT Count() FROM Final_Team__c]);

        //when
        Test.startTest();
        delete nuzlocke;
        Test.stopTest();

        //then
        System.assertEquals(0, [SELECT Count() FROM Nuzlocke__c]);
        System.assertEquals(0, [SELECT Count() FROM Final_Team__c]);
    }
}