temp/objects/Final_Team__c.object
<CustomObject>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Final Teams</relationshipLabel>
        <relationshipName>Final_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Final_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <formula>Pokemon__r.Form__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Form</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pokemon__c</fullName>
        <label>Pokemon</label>
        <referenceTo>Pokemon__c</referenceTo>
        <relationshipLabel>Final Team Members</relationshipLabel>
        <relationshipName>Final_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Final Team Member</label>
    <nameField>
        <displayFormat>FTM-{000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Hero__c.object
<CustomObject>
    <fields>
        <fullName>Game_Version__c</fullName>
        <label>Game Version</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pokemon_Game_Versions</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                    <default>true</default>
                    <label>Male</label>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Game_Version__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Kanto</fullName>
                </value>
                <value>
                    <fullName>Johto</fullName>
                </value>
                <value>
                    <fullName>Hoenn</fullName>
                </value>
                <value>
                    <fullName>Sinnoh</fullName>
                </value>
                <value>
                    <fullName>Unova</fullName>
                </value>
                <value>
                    <fullName>Kalos</fullName>
                </value>
                <value>
                    <fullName>Alola</fullName>
                </value>
                <value>
                    <fullName>Galar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Nuzlocke__c.object
<CustomObject>
    <fields>
        <fullName>Allowed_Catching_Methods_Per_Area__c</fullName>
        <label>Allowed Catching Methods / Area</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Breeding (1)</fullName>
                </value>
                <value>
                    <fullName>Breeding (Any)</fullName>
                </value>
                <value>
                    <fullName>Breeding (One/Parent)</fullName>
                </value>
                <value>
                    <fullName>Breeding (One/Type)</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Fossil (1)</fullName>
                </value>
                <value>
                    <fullName>Fossil (Any)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (1)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (2)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (3)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (4)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (Any)</fullName>
                </value>
                <value>
                    <fullName>Headbutt</fullName>
                </value>
                <value>
                    <fullName>Land</fullName>
                </value>
                <value>
                    <fullName>Land/Water</fullName>
                </value>
                <value>
                    <fullName>Trade</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Water/Headbutt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Game_Version__c</fullName>
        <formula>TEXT(Hero__r.Game_Version__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Game Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hero__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Hero</label>
        <referenceTo>Hero__c</referenceTo>
        <relationshipLabel>Nuzlockes</relationshipLabel>
        <relationshipName>Nuzlockes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legendaries_Rule__c</fullName>
        <label>Legendaries Rule</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Catch - no use</fullName>
                </value>
                <value>
                    <fullName>Catch - use</fullName>
                </value>
                <value>
                    <fullName>Kill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Multiple_Elite_Four_Fights__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if Nuzlocke run involves more than one Elite Four fights, thus assembling more than one final team</description>
        <inlineHelpText>Check, if Nuzlocke run involves more than one Elite Four fights, thus assembling more than one final team</inlineHelpText>
        <label>Multiple Elite Four Fights</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pokemon__c.object
<CustomObject>
    <fields>
        <fullName>Caught_Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Caught Form</label>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons (Caught)</relationshipLabel>
        <relationshipName>Caught_Pokemons</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Genderless</fullName>
                    <default>true</default>
                    <label>Genderless</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pokemon_Data__c.object
<CustomObject>
    <fields>
        <fullName>Family_Stage__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Family Stage</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abra</fullName>
                </value>
                <value>
                    <fullName>Absol</fullName>
                </value>
                <value>
                    <fullName>Aerodactyl</fullName>
                </value>
                <value>
                    <fullName>Aipom</fullName>
                </value>
                <value>
                    <fullName>Alomomola</fullName>
                </value>
                <value>
                    <fullName>Amaura</fullName>
                </value>
                <value>
                    <fullName>Anorith</fullName>
                </value>
                <value>
                    <fullName>Arceus</fullName>
                </value>
                <value>
                    <fullName>Archen</fullName>
                </value>
                <value>
                    <fullName>Aron</fullName>
                </value>
                <value>
                    <fullName>Articuno</fullName>
                </value>
                <value>
                    <fullName>Audino</fullName>
                </value>
                <value>
                    <fullName>Axew</fullName>
                </value>
                <value>
                    <fullName>Azelf</fullName>
                </value>
                <value>
                    <fullName>Azurill</fullName>
                </value>
                <value>
                    <fullName>Bagon</fullName>
                </value>
                <value>
                    <fullName>Baltoy</fullName>
                </value>
                <value>
                    <fullName>Barboach</fullName>
                </value>
                <value>
                    <fullName>Basculin</fullName>
                </value>
                <value>
                    <fullName>Beldum</fullName>
                </value>
                <value>
                    <fullName>Bellsprout</fullName>
                </value>
                <value>
                    <fullName>Bergmite</fullName>
                </value>
                <value>
                    <fullName>Bidoof</fullName>
                </value>
                <value>
                    <fullName>Binacle</fullName>
                </value>
                <value>
                    <fullName>Blacephalon</fullName>
                </value>
                <value>
                    <fullName>Blitzle</fullName>
                </value>
                <value>
                    <fullName>Bonsly</fullName>
                </value>
                <value>
                    <fullName>Bouffalant</fullName>
                </value>
                <value>
                    <fullName>Bounsweet</fullName>
                </value>
                <value>
                    <fullName>Bronzor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pokedex_Number__c</fullName>
        <defaultValue>TEXT(000)</defaultValue>
        <externalId>true</externalId>
        <label>Pokedex Number</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Type__c</fullName>
        <label>Primary Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pokemon_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region_Specific_Variants__c</fullName>
        <description>Does the Pokemon has any region specific variant?</description>
        <label>Available Region Specific Variants</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alolan</fullName>
                </value>
                <value>
                    <fullName>Galarian</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Pokemon_Data__c.object
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <description>Standard form of the Pokemon species</description>
        <label>Form</label>
    </recordTypes>

force-app/main/default/globalValueSets/Pokemon_Game_Versions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Yellow</fullName>
    </customValue>
    <customValue>
        <fullName>Fire Red</fullName>
    </customValue>
    <customValue>
        <fullName>Leaf Green</fullName>
    </customValue>
    <customValue>
        <fullName>Gold</fullName>
    </customValue>
    <customValue>
        <fullName>Silver</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal</fullName>
    </customValue>
    <customValue>
        <fullName>Heart Gold</fullName>
    </customValue>
    <customValue>
        <fullName>Soul Silver</fullName>
    </customValue>
    <customValue>
        <fullName>Ruby</fullName>
    </customValue>
    <customValue>
        <fullName>Sapphire</fullName>
    </customValue>
    <customValue>
        <fullName>Emerald</fullName>
    </customValue>
    <customValue>
        <fullName>Omega Ruby</fullName>
    </customValue>
    <customValue>
        <fullName>Alpha Sapphire</fullName>
    </customValue>
    <customValue>
        <fullName>Diamond</fullName>
    </customValue>
    <customValue>
        <fullName>Pearl</fullName>
    </customValue>
    <customValue>
        <fullName>Platinum</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>Black 2</fullName>
    </customValue>
    <customValue>
        <fullName>White 2</fullName>
    </customValue>
    <customValue>
        <fullName>X</fullName>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
    </customValue>
    <customValue>
        <fullName>Sun</fullName>
    </customValue>
    <customValue>
        <fullName>Moon</fullName>
    </customValue>
    <customValue>
        <fullName>Ultra Sun</fullName>
    </customValue>
    <customValue>
        <fullName>Ultra Moon</fullName>
    </customValue>
    <customValue>
        <fullName>Let&apos;s GO Pikachu</fullName>
    </customValue>
    <masterLabel>Pokemon Game Versions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Pokemon_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>???</fullName>
    </customValue>
    <customValue>
        <fullName>Bug</fullName>
    </customValue>
    <customValue>
        <fullName>Dark</fullName>
    </customValue>
    <customValue>
        <fullName>Dragon</fullName>
    </customValue>
    <customValue>
        <fullName>Electric</fullName>
    </customValue>
    <customValue>
        <fullName>Fairy</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>Fire</fullName>
    </customValue>
    <customValue>
        <fullName>Flying</fullName>
    </customValue>
    <customValue>
        <fullName>Ghost</fullName>
    </customValue>
    <customValue>
        <fullName>Grass</fullName>
    </customValue>
    <customValue>
        <fullName>Ground</fullName>
    </customValue>
    <customValue>
        <fullName>Ice</fullName>
    </customValue>
    <customValue>
        <fullName>Normal</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Psychic</fullName>
    </customValue>
    <customValue>
        <fullName>Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Steel</fullName>
    </customValue>
    <customValue>
        <fullName>Water</fullName>
    </customValue>
    <description>List of all Pokemon types</description>
    <masterLabel>Pokemon Type</masterLabel>
</GlobalValueSet>

src/classes/PMHR_TestDataFactory.cls
@IsTest
public class PMHR_TestDataFactory {
    public static Hero__c createHeroObject(String name, String region) {
        return createHeroObject(name, region, PMHR_Utilities.HERO_GAME_VERSION_RED);
    }

    public static Hero__c createHeroObject(String name, String region, String gameVersion) {
        Hero__c hero = new Hero__c();
        hero.Name = name;
        hero.Region__c = region;
        hero.Game_Version__c = gameVersion;

        return hero;
    }

    public static Nuzlocke__c createNuzlockeObject(String name, Date startDate, Id heroId) {
        return createNuzlockeObject(name, startDate, PMHR_Utilities.POKEMON_CATCH_METHOD_EVENT, heroId, PMHR_Utilities.NUZLOCKE_LEGENDARIES_RULE_KILL, false);
    }

    public static Nuzlocke__c createNuzlockeObject(String name, Date startDate, Id heroId, Boolean multipleEliteFourFights) {
        return createNuzlockeObject(name, startDate, PMHR_Utilities.POKEMON_CATCH_METHOD_EVENT, heroId, PMHR_Utilities.NUZLOCKE_LEGENDARIES_RULE_KILL, multipleEliteFourFights);
    }

    public static Nuzlocke__c createNuzlockeObject(String name, Date startDate, String allowedCatchingMethods, Id heroId, String legendariesRule, Boolean multipleEliteFourFights) {
        Nuzlocke__c nuzlocke = new Nuzlocke__c();
        nuzlocke.Name = name;
        nuzlocke.Start_Date__c = startDate;
        nuzlocke.Allowed_Catching_Methods_Per_Area__c = allowedCatchingMethods;
        nuzlocke.Hero__c = heroId;
        nuzlocke.Legendaries_Rule__c = legendariesRule;
        nuzlocke.Multiple_Elite_Four_Fights__c = multipleEliteFourFights;

        return nuzlocke;
    }

    public static Pokemon_Data__c createPokemonDataObject(String pokedexNr, String form, String formType, String family, Integer familyStage) {
        Pokemon_Data__c pokemonData = new Pokemon_Data__c();
        pokemonData.Pokedex_Number__c = pokedexNr;
        pokemonData.Name = form;
        pokemonData.Primary_Type__c = formType;
        pokemonData.Family__c = family;
        pokemonData.Family_Stage__c = familyStage;
        List<String> variants = new List<String>();
        for (PicklistEntry variant : PMHR_Utilities.POKEMON_REGIONAL_VARIANT) {
            if (variant.getValue() != PMHR_Utilities.REGION_VARIANT_STANDARD) {
                variants.add(variant.getValue());
            }
        }
        pokemonData.Region_Specific_Variants__c = String.join(variants, ';');

        return pokemonData;
    }

    public static Pokemon__c createPokemonObject(String name, String gender, Id caughtFormId, String catchMethod, Id nuzlockeId) {
        return createPokemonObject(name, gender, caughtFormId, null, catchMethod, nuzlockeId, PMHR_Utilities.REGION_VARIANT_STANDARD);
    }

    public static Pokemon__c createPokemonObject(String name, String gender, Id caughtFormId, Id formId, String catchMethod, Id nuzlockeId, String variant) {
        Pokemon__c pokemon = new Pokemon__c();
        pokemon.Name = name;
        pokemon.Gender__c = gender;
        pokemon.Caught_Form__c = caughtFormId;
        pokemon.Form__c = formId;
        pokemon.Catch_Method__c = catchMethod;
        pokemon.Nuzlocke__c = nuzlockeId;
        pokemon.Variant__c = variant;

        return pokemon;
    }

    public static Final_Team__c createFinalTeamObject(String name, Id nuzlockeId) {
        Final_Team__c finalTeam = new Final_Team__c();

        finalTeam.Name = name;
        finalTeam.Nuzlocke__c = nuzlockeId;

        return finalTeam;
    }

    public static Final_Team_Member__c createFinalTeamMemberObject(Id finalTeamId, Id pokemonId) {
        Final_Team_Member__c finalTeamMember = new Final_Team_Member__c();

        finalTeamMember.Final_Team__c = finalTeamId;
        finalTeamMember.Pokemon__c = pokemonId;

        return finalTeamMember;
    }
}