temp/objects/Final_Team__c.object
<CustomObject>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Final_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Ability__c</fullName>
        <label>Ability</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Team__c</fullName>
        <label>Final Team</label>
        <referenceTo>Final_Team__c</referenceTo>
        <relationshipLabel>Final Team Members</relationshipLabel>
        <relationshipName>Final_Team_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <formula>Pokemon__r.Form__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Form</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Held_Item__c</fullName>
        <label>Held Item</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Move_1__c</fullName>
        <label>Move 1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Move_2__c</fullName>
        <label>Move 2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Move_3__c</fullName>
        <label>Move 3</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Move_4__c</fullName>
        <label>Move 4</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nature__c</fullName>
        <label>Nature</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pokemon__c</fullName>
        <label>Pokemon</label>
        <referenceTo>Pokemon__c</referenceTo>
        <relationshipLabel>Final Team Members</relationshipLabel>
        <relationshipName>Final_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>Pokemon__r.Form__r.Type__c</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Final Team Member</label>
    <nameField>
        <displayFormat>FTM-{000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Pokemon__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
        <label>Form</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Pokemon_Data__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PMHR_FinalTeamMemberQueryService.cls
public with sharing class PMHR_FinalTeamMemberQueryService {
    public static Final_Team_Member__c getFinalTeamMemberById(Id finalTeamMemberId) {
        return [
                SELECT Id, Form__c, Ability__c, Nature__c, Held_Item__c, Final_Team__c, Pokemon__c, Level__c, Type__c,
                        Move_1__c, Move_2__c, Move_3__c, Move_4__c
                FROM Final_Team_Member__c
                WHERE Id = :finalTeamMemberId
                LIMIT 1];
    }
}