temp/objects/Final_Team__c.object
<CustomObject>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Final Teams</relationshipLabel>
        <relationshipName>Final_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Final_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Final_Team__c</fullName>
        <label>Final Team</label>
        <referenceTo>Final_Team__c</referenceTo>
        <relationshipLabel>Final Team Members</relationshipLabel>
        <relationshipName>Final_Team_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <formula>Pokemon__r.Form__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Form</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pokemon__c</fullName>
        <label>Pokemon</label>
        <referenceTo>Pokemon__c</referenceTo>
        <relationshipLabel>Final Team Members</relationshipLabel>
        <relationshipName>Final_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF(Pokemon__r.Is_Alolan__c, Pokemon__r.Form__r.Alolan_Type__c, Pokemon__r.Form__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Final Team Member</label>
    <nameField>
        <displayFormat>FTM-{000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Nuzlocke__c.object
<CustomObject>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pokemon__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
        <label>Form</label>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PMHR_FinalTeamListController.cls
public class PMHR_FinalTeamListController {

    @AuraEnabled
    public static List<FinalTeam> getFinalTeamInfo(Id nuzlockeId) {
        List<FinalTeam> result = new List<FinalTeam>();
        List<Final_Team__c> finalTeams = [SELECT Id, Name, (SELECT Id, Name, Pokemon__c, Pokemon__r.Name, Form__c, Type__c, Level__c FROM Final_Team_Members__r ORDER BY Name) FROM Final_Team__c WHERE Nuzlocke__c = :nuzlockeId ORDER BY CreatedDate];
        for (Final_Team__c finalTeam : finalTeams) {
            List<FinalTeamMember> finalTeamMembers = new List<FinalTeamMember>();
            for (Final_Team_Member__c member : finalTeam.Final_Team_Members__r) {
                finalTeamMembers.add(new FinalTeamMember(member));
            }

            result.add(new FinalTeam(finalTeam, finalTeamMembers));
        }

        return result;
    }

    @TestVisible
    private class FinalTeam {
        @AuraEnabled public Id id { get; private set; }
        @AuraEnabled public String name { get; private set; }
        @AuraEnabled public List<FinalTeamMember> members { get; private set; }

        public FinalTeam(Final_Team__c finalTeam, List<FinalTeamMember> members) {
            this.id = finalTeam.Id;
            this.name = finalTeam.Name;
            this.members = members;
        }
    }

    @TestVisible
    private class FinalTeamMember {
        @AuraEnabled public Id id { get; private set; }
        @AuraEnabled public String nr { get; private set; }
        @AuraEnabled public String pokemonName { get; private set; }
        @AuraEnabled public Id pokemonId { get; private set; }
        @AuraEnabled public String form { get; private set; }
        @AuraEnabled public String type { get; private set; }
        @AuraEnabled public Integer level { get; private set; }

        public FinalTeamMember(Final_Team_Member__c member) {
            this.id = member.Id;
            this.nr = member.Name;
            this.pokemonName = member.Pokemon__r.Name;
            this.pokemonId = member.Pokemon__c;
            this.form = member.Form__c;
            this.type = member.Type__c;
            this.level = Integer.valueOf(member.Level__c);
        }
    }
}