temp/objects/Final_Team__c.object
<CustomObject>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Final Teams</relationshipLabel>
        <relationshipName>Final_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Nuzlocke__c.object
<CustomObject>
    <fields>
        <fullName>End_Status__c</fullName>
        <label>End Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Finished__c</fullName>
        <description>Indicate if Nuzlocke is finished</description>
        <formula>AND(
 NOT(ISBLANK(End_Date__c)),
 NOT(ISBLANK(TEXT(End_Status__c)))
)</formula>
        <label>Is Finished</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Multiple_Elite_Four_Fights__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if Nuzlocke run involves more than one Elite Four fights, thus assembling more than one final team</description>
        <inlineHelpText>Check, if Nuzlocke run involves more than one Elite Four fights, thus assembling more than one final team</inlineHelpText>
        <label>Multiple Elite Four Fights</label>
        <type>Checkbox</type>
    </fields>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PMHR_TriggerHandlerNuzlocke_Helper.cls
public class PMHR_TriggerHandlerNuzlocke_Helper {
    public static Map<Id, Nuzlocke__c> getNuzlockesWithFinalTeamsList(Set<Id> nuzlockesIds) {
        return new Map<Id, Nuzlocke__c>(PMHR_NuzlockeQueryService.getNuzlockesWithFinalTeamsByIds(nuzlockesIds));
    }

    public static void validateFinishingNuzlocke(Nuzlocke__c oldVersion, Nuzlocke__c newVersion) {
        if (oldVersion.End_Status__c != newVersion.End_Status__c
                && newVersion.End_Status__c == PMHR_NuzlockeBuilder.END_STATUS_SUCCESS
                && oldVersion.Final_Teams__r.isEmpty()) {
            newVersion.addError(Label.Toast_Error_Nuzlocke_Finished_With_Success_Without_Final_Team);
        }
    }

    public static void markNuzlockeAsFinishedWithSuccess(Nuzlocke__c nuzlocke) {
        if (!nuzlocke.Multiple_Elite_Four_Fights__c) {
            setNuzlockeEndData(nuzlocke, Date.today(), PMHR_NuzlockeBuilder.END_STATUS_SUCCESS);
        }
    }

    public static void markNuzlockeAsNotFinished(Nuzlocke__c nuzlocke) {
        if (nuzlocke.Final_Teams__r.isEmpty() && nuzlocke.Is_Finished__c) {
            setNuzlockeEndData(nuzlocke, null, null);
        }
    }

    private static void setNuzlockeEndData(Nuzlocke__c nuzlocke, Date endDate, String endStatus) {
        nuzlocke = new PMHR_NuzlockeBuilder(nuzlocke)
                .setEndDate(endDate)
                .setEndStatus(endStatus)
                .build();
    }
}