temp/objects/Hero__c.object
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Nuzlocke__c.object
<CustomObject>
    <fields>
        <fullName>Allowed_Catching_Methods_Per_Area__c</fullName>
        <label>Allowed Catching Methods / Area</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Breeding (1)</fullName>
                </value>
                <value>
                    <fullName>Breeding (Any)</fullName>
                </value>
                <value>
                    <fullName>Breeding (One/Parent)</fullName>
                </value>
                <value>
                    <fullName>Breeding (One/Type)</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Fossil (1)</fullName>
                </value>
                <value>
                    <fullName>Fossil (Any)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (1)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (2)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (3)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (4)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (Any)</fullName>
                </value>
                <value>
                    <fullName>Grass</fullName>
                </value>
                <value>
                    <fullName>Grass/Overworld</fullName>
                </value>
                <value>
                    <fullName>Grass/Water</fullName>
                </value>
                <value>
                    <fullName>Overworld</fullName>
                </value>
                <value>
                    <fullName>Trade</fullName>
                </value>
                <value>
                    <fullName>Tree</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Water/Tree</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Status__c</fullName>
        <label>End Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hero__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Hero</label>
        <referenceTo>Hero__c</referenceTo>
        <relationshipLabel>Nuzlockes</relationshipLabel>
        <relationshipName>Nuzlockes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legendaries_Rule__c</fullName>
        <label>Legendaries Rule</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Catch - no use</fullName>
                </value>
                <value>
                    <fullName>Catch - use</fullName>
                </value>
                <value>
                    <fullName>Kill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Multiple_Elite_Four_Fights__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if Nuzlocke run involves more than one Elite Four fights, thus assembling more than one final team</description>
        <inlineHelpText>Check, if Nuzlocke run involves more than one Elite Four fights, thus assembling more than one final team</inlineHelpText>
        <label>Multiple Elite Four Fights</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Safari_Zone_Rule__c</fullName>
        <label>Safari Zone Rule</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Amount of areas/Safari</fullName>
                </value>
                <value>
                    <fullName>One/Area</fullName>
                </value>
                <value>
                    <fullName>One/Safari</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PMHR_NuzlockeBuilder_Test.cls
@IsTest
private class PMHR_NuzlockeBuilder_Test {
    static testMethod void shouldBuildNuzlocke() {
        //given
        String name = 'Nuzlocke';
        Hero__c hero = new PMHR_HeroBuilder()
                .save();
        Date startDate = Date.today().addDays(-1);
        Date endDate = Date.today();
        Boolean isMultipleEliteFourFights = false;

        //when
        Nuzlocke__c nuzlocke = new PMHR_NuzlockeBuilder()
                .setName(name)
                .setHero(hero.Id)
                .setStartDate(startDate)
                .setAllwoedCatchMethodsPerArea(new List<String> {PMHR_NuzlockeBuilder.POKEMON_CATCH_METHOD_EVENT})
                .setLegendariesRule(PMHR_NuzlockeBuilder.LEGENDARIES_RULE_KILL)
                .setSafariZoneRule(PMHR_NuzlockeBuilder.SAFARI_ZONE_RULE_ONE_PER_AREA)
                .setMultipleEliteFourFights(isMultipleEliteFourFights)
                .save();

        nuzlocke = new PMHR_NuzlockeBuilder(nuzlocke)
                .setEndDate(endDate)
                .setEndStatus(PMHR_NuzlockeBuilder.END_STATUS_FAILED)
                .save();

        //then
        nuzlocke = PMHR_NuzlockeQueryService.getNuzlockeById(nuzlocke.Id);
        System.assertEquals(name, nuzlocke.Name);
        System.assertEquals(hero.Id, nuzlocke.Hero__c);
        System.assertEquals(startDate, nuzlocke.Start_Date__c);
        System.assertEquals(PMHR_NuzlockeBuilder.POKEMON_CATCH_METHOD_EVENT, nuzlocke.Allowed_Catching_Methods_Per_Area__c);
        System.assertEquals(PMHR_NuzlockeBuilder.LEGENDARIES_RULE_KILL, nuzlocke.Legendaries_Rule__c);
        System.assertEquals(PMHR_NuzlockeBuilder.SAFARI_ZONE_RULE_ONE_PER_AREA, nuzlocke.Safari_Zone_Rule__c);
        System.assertEquals(isMultipleEliteFourFights, nuzlocke.Multiple_Elite_Four_Fights__c);
        System.assertEquals(endDate, nuzlocke.End_Date__c);
        System.assertEquals(PMHR_NuzlockeBuilder.END_STATUS_FAILED, nuzlocke.End_Status__c);
    }

    static testMethod void shouldThrowExceptionNullAllowedCatchMethods() {
        //given
        Boolean errorOccurred = false;

        //when
        try {
            Nuzlocke__c nuzlocke = new PMHR_NuzlockeBuilder()
                    .setAllwoedCatchMethodsPerArea(null)
                    .build();
        } catch (PMHR_NuzlockeBuilder.NullAllowedCatchMethodsException ex) {
            errorOccurred = true;
        }

        //then
        System.assert(errorOccurred);
    }
}