temp/objects/Hero__c.object
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Nuzlocke__c.object
<CustomObject>
    <fields>
        <fullName>Hero__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Hero</label>
        <referenceTo>Hero__c</referenceTo>
        <relationshipLabel>Nuzlockes</relationshipLabel>
        <relationshipName>Nuzlockes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Pokemon__c.object
<CustomObject>
    <fields>
        <fullName>Caught_Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Caught Form</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Pokemon_Data__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons (Caught)</relationshipLabel>
        <relationshipName>Caught_Pokemons</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
        <label>Form</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Pokemon_Data__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region_Specific_Variant__c</fullName>
        <label>Region Specific Variant</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Pokemon_Data__c.object
<CustomObject>
    <fields>
        <fullName>Family_Stage__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Family Stage</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abra</fullName>
                </value>
                <value>
                    <fullName>Absol</fullName>
                </value>
                <value>
                    <fullName>Aerodactyl</fullName>
                </value>
                <value>
                    <fullName>Aipom</fullName>
                </value>
                <value>
                    <fullName>Alomomola</fullName>
                </value>
                <value>
                    <fullName>Amaura</fullName>
                </value>
                <value>
                    <fullName>Anorith</fullName>
                </value>
                <value>
                    <fullName>Applin</fullName>
                </value>
                <value>
                    <fullName>Arceus</fullName>
                </value>
                <value>
                    <fullName>Archen</fullName>
                </value>
                <value>
                    <fullName>Arctovish</fullName>
                </value>
                <value>
                    <fullName>Arctozolt</fullName>
                </value>
                <value>
                    <fullName>Aron</fullName>
                </value>
                <value>
                    <fullName>Arrokuda</fullName>
                </value>
                <value>
                    <fullName>Articuno</fullName>
                </value>
                <value>
                    <fullName>Audino</fullName>
                </value>
                <value>
                    <fullName>Axew</fullName>
                </value>
                <value>
                    <fullName>Azelf</fullName>
                </value>
                <value>
                    <fullName>Azurill</fullName>
                </value>
                <value>
                    <fullName>Bagon</fullName>
                </value>
                <value>
                    <fullName>Baltoy</fullName>
                </value>
                <value>
                    <fullName>Barboach</fullName>
                </value>
                <value>
                    <fullName>Basculin</fullName>
                </value>
                <value>
                    <fullName>Beldum</fullName>
                </value>
                <value>
                    <fullName>Bellsprout</fullName>
                </value>
                <value>
                    <fullName>Bergmite</fullName>
                </value>
                <value>
                    <fullName>Bidoof</fullName>
                </value>
                <value>
                    <fullName>Binacle</fullName>
                </value>
                <value>
                    <fullName>Blacephalon</fullName>
                </value>
                <value>
                    <fullName>Blipbug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region_Specific_Variant__c</fullName>
        <label>Region Specific Variant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <description>Standard form of the Pokemon species</description>
        <label>Form</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Region_Specific_Pokemon_Variants.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Region Specific Pokemon Variants</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PMHR_TriggerHandlerPokemon_Test.cls
@IsTest
private class PMHR_TriggerHandlerPokemon_Test {
    @TestSetup static void setup() {
        Hero__c hero = new PMHR_HeroBuilder()
                .save();

        Nuzlocke__c nuzlocke = new PMHR_NuzlockeBuilder()
                .setHero(hero.Id)
                .save();

        List<Pokemon_Data__c> pokemonData = new List<Pokemon_Data__c>();
        for (Integer i = 1; i < 3; i++) {
            pokemonData.add(new PMHR_PokemonFormBuilder()
                    .setPokedexNumber('00' + i)
                    .setForm('Testor v' + i)
                    .setPrimaryType(PMHR_PokemonDataBuilder.TYPE_NORMAL)
                    .setFamily('Testor')
                    .setFamilyStage(i)
                    .build()
            );
        }
        pokemonData.add(new PMHR_PokemonFormBuilder()
                .setPokedexNumber('003')
                .setForm('Alestor')
                .setPrimaryType(PMHR_PokemonDataBuilder.TYPE_DARK)
                .setFamily('Alestor')
                .setFamilyStage(1)
                .build());
        insert pokemonData;
    }

    static testMethod void shouldCopyCaughtFormToFormOnInsert() {
        //given
        Pokemon_Data__c form = [SELECT Id FROM Pokemon_Data__c LIMIT 1];
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];

        //when
        Test.startTest();
        Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                .setCaughtForm(form.Id)
                .setNuzlocke(nuzlocke.Id)
                .save();
        Test.stopTest();

        //then
        newPokemon = [SELECT Caught_Form__c, Form__c FROM Pokemon__c LIMIT 1];
        System.assertEquals(newPokemon.Caught_Form__c, newPokemon.Form__c);
    }

    static testMethod void shouldNotCopyCaughtFormToFormOnInsert_formProvided() {
        //given
        List<Pokemon_Data__c> forms = [SELECT Id, Family_Stage__c FROM Pokemon_Data__c WHERE Family__c = 'Testor' LIMIT 2];
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];

        Pokemon_Data__c firstStageForm;
        Pokemon_Data__c secondStageForm;

        for (Pokemon_Data__c form : forms) {
            if (form.Family_Stage__c == 1) {
                firstStageForm = form;
            } else {
                secondStageForm = form;
            }
        }

        //when
        Test.startTest();
        Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                .setCaughtForm(firstStageForm.Id)
                .setForm(secondStageForm.Id)
                .setNuzlocke(nuzlocke.Id)
                .save();
        Test.stopTest();

        //then
        newPokemon = [SELECT Caught_Form__c, Form__c FROM Pokemon__c LIMIT 1];
        System.assertNotEquals(newPokemon.Caught_Form__c, newPokemon.Form__c);
        System.assertEquals(newPokemon.Caught_Form__c, firstStageForm.Id);
        System.assertEquals(newPokemon.Form__c, secondStageForm.Id);
    }

    static testMethod void shouldNotInsertPokemon_nuzlockeFinished() {
        //given
        Pokemon_Data__c form = [SELECT Id FROM Pokemon_Data__c LIMIT 1];
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        nuzlocke = new PMHR_NuzlockeBuilder(nuzlocke)
                .setEndDate(Date.today())
                .setEndStatus(PMHR_NuzlockeBuilder.END_STATUS_FAILED)
                .save();

        Boolean errorOccurred = false;

        //when
        Test.startTest();
        try {
            Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                    .setNuzlocke(nuzlocke.Id)
                    .setCaughtForm(form.Id)
                    .save();
        } catch (DmlException ex) {
            errorOccurred = true;
        }
        Test.stopTest();

        //then
        System.assert(errorOccurred);
        System.assertEquals(0, [SELECT Count() FROM Pokemon__c]);
    }

    static testMethod void shouldInsertPokemon_allowedVariant() {
        //given
        Pokemon_Data__c form = [SELECT Id FROM Pokemon_Data__c LIMIT 1];
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        Pokemon_Data__c additionalVariant = new PMHR_PokemonAdditionalVariantBuilder()
                .setVariantOf(form.Id)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .save();

        //when
        Test.startTest();
        Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                .setNuzlocke(nuzlocke.Id)
                .setCaughtForm(form.Id)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .save();
        Test.stopTest();

        //then
        System.assertEquals(1, [SELECT Count() FROM Pokemon__c]);
    }

    static testMethod void shouldNotInsertPokemon_forbiddenVariant() {
        //given
        Pokemon_Data__c form = [SELECT Id FROM Pokemon_Data__c LIMIT 1];
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];

        Boolean errorOccurred = false;

        //when
        Test.startTest();
        try {
            Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                    .setNuzlocke(nuzlocke.Id)
                    .setCaughtForm(form.Id)
                    .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                    .save();
        } catch (DmlException ex) {
            errorOccurred = true;
        }
        Test.stopTest();

        //then
        System.assert(errorOccurred);
        System.assertEquals(0, [SELECT Count() FROM Pokemon__c]);
    }

    static testMethod void shouldUpdatePokemon_allowedVariant() {
        //given
        Pokemon_Data__c form = [SELECT Id FROM Pokemon_Data__c LIMIT 1];
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        Pokemon_Data__c additionalVariant = new PMHR_PokemonAdditionalVariantBuilder()
                .setVariantOf(form.Id)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .save();
        Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                .setNuzlocke(nuzlocke.Id)
                .setCaughtForm(form.Id)
                .save();

        //when
        Test.startTest();
        newPokemon = new PMHR_PokemonBuilder(newPokemon)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .save();
        Test.stopTest();

        //then
        newPokemon = PMHR_PokemonQueryService.getPokemonById(newPokemon.Id);
        System.assertEquals(PMHR_Utilities.REGION_VARIANT_ALOLAN, newPokemon.Region_Specific_Variant__c);
    }

    static testMethod void shouldNotUpdatePokemon_forbiddenVariant() {
        //given
        Pokemon_Data__c form = [SELECT Id FROM Pokemon_Data__c LIMIT 1];
        Nuzlocke__c nuzlocke = [SELECT Id FROM Nuzlocke__c LIMIT 1];
        Pokemon__c newPokemon = new PMHR_PokemonBuilder()
                .setNuzlocke(nuzlocke.Id)
                .setCaughtForm(form.Id)
                .save();

        Boolean errorOccurred = false;

        //when
        Test.startTest();
        try {
            newPokemon = new PMHR_PokemonBuilder(newPokemon)
                    .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                    .save();
        } catch (DmlException ex) {
            errorOccurred = true;
        }
        Test.stopTest();

        //then
        newPokemon = PMHR_PokemonQueryService.getPokemonById(newPokemon.Id);
        System.assertNotEquals(PMHR_Utilities.REGION_VARIANT_ALOLAN, newPokemon.Region_Specific_Variant__c);
    }
}