temp/objects/Hero__c.object
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_FinalTeam__c/PMHR_FinalTeam__c.object-meta.xml
<CustomObject>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_FinalTeam__c/fields/Nuzlocke__c.field-meta.xml
<CustomField>
    <fullName>Nuzlocke__c</fullName>
    <label>Nuzlocke</label>
    <referenceTo>PMHR_Nuzlocke__c</referenceTo>
    <relationshipLabel>Final Teams</relationshipLabel>
    <relationshipName>FinalTeams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/PMHR_Nuzlocke__c.object-meta.xml
<CustomObject>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/AllowedCatchingMethodsPerArea__c.field-meta.xml
<CustomField>
    <fullName>AllowedCatchingMethodsPerArea__c</fullName>
    <label>Allowed Catching Methods / Area</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BreedingOnlyOnce</fullName>
                <label>Breeding (Only Once)</label>
            </value>
            <value>
                <fullName>BreedingAny</fullName>
                <label>Breeding (Any)</label>
            </value>
            <value>
                <fullName>BreedingOnePerParent</fullName>
                <label>Breeding (One/Parent)</label>
            </value>
            <value>
                <fullName>BreedingOnePerType</fullName>
                <label>Breeding (One/Type)</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>FossilOnlyOne</fullName>
                <label>Fossil (Only One)</label>
            </value>
            <value>
                <fullName>FossilAny</fullName>
                <label>Fossil (Any)</label>
            </value>
            <value>
                <fullName>GameCornerMax1</fullName>
                <label>Game Corner (Max 1)</label>
            </value>
            <value>
                <fullName>GameCornerMax2</fullName>
                <label>Game Corner (Max 2)</label>
            </value>
            <value>
                <fullName>GameCornerMax3</fullName>
                <label>Game Corner (Max 3)</label>
            </value>
            <value>
                <fullName>GameCornerMax4</fullName>
                <label>Game Corner (Max 4)</label>
            </value>
            <value>
                <fullName>GameCornerAny</fullName>
                <label>Game Corner (Any)</label>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>GrassOrOverworld</fullName>
                <label>Grass/Overworld</label>
            </value>
            <value>
                <fullName>GrassOrWater</fullName>
                <label>Grass/Water</label>
            </value>
            <value>
                <fullName>Overworld</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>Tree</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>WaterOrTree</fullName>
                <label>Water/Tree</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/GameVersion__c.field-meta.xml
<CustomField>
    <fullName>GameVersion__c</fullName>
    <formula>TEXT(Hero__r.GameVersion__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Game Version</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hero</label>
    <referenceTo>PMHR_Hero__c</referenceTo>
    <relationshipLabel>Nuzlockes</relationshipLabel>
    <relationshipName>Nuzlockes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/IsFinished__c.field-meta.xml
<CustomField>
    <fullName>IsFinished__c</fullName>
    <description>Indicate if Nuzlocke is finished</description>
    <formula>AND(
 NOT(ISBLANK(EndDate__c)),
 NOT(ISPICKVAL(Status__c, &apos;InProgress&apos;))
)</formula>
    <label>Finished</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/LegendariesRule__c.field-meta.xml
<CustomField>
    <fullName>LegendariesRule__c</fullName>
    <inlineHelpText>Rules regarding the Legendary Pokemon.</inlineHelpText>
    <label>Legendaries Rule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CatchNoUse</fullName>
                <label>Catch - no use</label>
            </value>
            <value>
                <fullName>CatchUse</fullName>
                <label>Catch - use</label>
            </value>
            <value>
                <fullName>Kill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/PokemonsCaught__c.field-meta.xml
<CustomField>
    <fullName>PokemonsCaught__c</fullName>
    <description>Number of caught Pokemons</description>
    <label>Pokemons Caught</label>
    <summaryForeignKey>PMHR_Pokemon__c.Nuzlocke__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/PokemonsDeceased__c.field-meta.xml
<CustomField>
    <fullName>PokemonsDeceased__c</fullName>
    <description>Number of Pokemons lost in battle</description>
    <label>Pokemons Deceased</label>
    <summaryFilterItems>
        <field>PMHR_Pokemon__c.IsDeceased__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>PMHR_Pokemon__c.Nuzlocke__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/RivalName__c.field-meta.xml
<CustomField>
    <fullName>RivalName__c</fullName>
    <formula>Hero__r.RivalName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rival Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/SafariZoneRule__c.field-meta.xml
<CustomField>
    <fullName>SafariZoneRule__c</fullName>
    <label>Safari Zone Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OnePerArea</fullName>
                <label>One/Area</label>
            </value>
            <value>
                <fullName>OnePerSafari</fullName>
                <label>One/Safari</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InProgress</fullName>
                <default>true</default>
                <label>In progress</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/services/PMHR_NuzlockeQueryService.cls
public with sharing class PMHR_NuzlockeQueryService {
    public static PMHR_Nuzlocke__c getNuzlockeById(Id nuzlockeId) {
        return [
                SELECT Id, Name, StartDate__c, EndDate__c, Status__c, Hero__c, RivalName__c,
                        AllowedCatchingMethodsPerArea__c, LegendariesRule__c, SafariZoneRule__c,
                        GameVersion__c, IsFinished__c, Multiple_Elite_Four_Fights__c, PokemonsCaught__c, PokemonsDeceased__c
                FROM PMHR_Nuzlocke__c
                WHERE Id = :nuzlockeId
                LIMIT 1
        ];
    }

    public static List<PMHR_Nuzlocke__c> getNuzlockesWithFinalTeamsByIds(Set<Id> nuzlockeIds) {
        return [
                SELECT Id, Name, StartDate__c, EndDate__c, Status__c, Hero__c, RivalName__c,
                        AllowedCatchingMethodsPerArea__c, LegendariesRule__c, SafariZoneRule__c,
                        GameVersion__c, IsFinished__c, Multiple_Elite_Four_Fights__c, PokemonsCaught__c, PokemonsDeceased__c,
                    (SELECT Name FROM FinalTeams__r)
                FROM PMHR_Nuzlocke__c
                WHERE Id IN :nuzlockeIds
        ];
    }

    public static PMHR_Nuzlocke__c getNuzlockeWithFinalTeamsById(Id nuzlockeId) {
        return getNuzlockesWithFinalTeamsByIds(new Set<Id>{nuzlockeId}).get(0);
    }
}