temp/objects/Hero__c.object
<CustomObject>
    <fields>
        <fullName>Game_Version__c</fullName>
        <label>Game Version</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pokemon_Game_Versions</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                    <default>true</default>
                    <label>Male</label>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nickname__c</fullName>
        <label>Nickname</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Game_Version__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Kanto</fullName>
                </value>
                <value>
                    <fullName>Johto</fullName>
                </value>
                <value>
                    <fullName>Hoenn</fullName>
                </value>
                <value>
                    <fullName>Sinnoh</fullName>
                </value>
                <value>
                    <fullName>Unova</fullName>
                </value>
                <value>
                    <fullName>Kalos</fullName>
                </value>
                <value>
                    <fullName>Alola</fullName>
                </value>
                <value>
                    <fullName>Galar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rival_Name__c</fullName>
        <label>Rival Name</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Pokemon_Game_Versions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Yellow</fullName>
    </customValue>
    <customValue>
        <fullName>Fire Red</fullName>
    </customValue>
    <customValue>
        <fullName>Leaf Green</fullName>
    </customValue>
    <customValue>
        <fullName>Gold</fullName>
    </customValue>
    <customValue>
        <fullName>Silver</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal</fullName>
    </customValue>
    <customValue>
        <fullName>Heart Gold</fullName>
    </customValue>
    <customValue>
        <fullName>Soul Silver</fullName>
    </customValue>
    <customValue>
        <fullName>Ruby</fullName>
    </customValue>
    <customValue>
        <fullName>Sapphire</fullName>
    </customValue>
    <customValue>
        <fullName>Emerald</fullName>
    </customValue>
    <customValue>
        <fullName>Omega Ruby</fullName>
    </customValue>
    <customValue>
        <fullName>Alpha Sapphire</fullName>
    </customValue>
    <customValue>
        <fullName>Diamond</fullName>
    </customValue>
    <customValue>
        <fullName>Pearl</fullName>
    </customValue>
    <customValue>
        <fullName>Platinum</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>Black 2</fullName>
    </customValue>
    <customValue>
        <fullName>White 2</fullName>
    </customValue>
    <customValue>
        <fullName>X</fullName>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
    </customValue>
    <customValue>
        <fullName>Sun</fullName>
    </customValue>
    <customValue>
        <fullName>Moon</fullName>
    </customValue>
    <customValue>
        <fullName>Ultra Sun</fullName>
    </customValue>
    <customValue>
        <fullName>Ultra Moon</fullName>
    </customValue>
    <customValue>
        <fullName>Let&apos;s GO Pikachu</fullName>
    </customValue>
    <masterLabel>Pokemon Game Versions</masterLabel>
</GlobalValueSet>

temp/classes/PMHR_HeroBuilder.cls
public with sharing class PMHR_HeroBuilder {
    public static final String GAME_VERSION_RED = 'Red';

    public static final String REGION_KANTO = 'Kanto';

    private Hero__c record;

    private Hero__c defaultData() {
        return new Hero__c(
                Name = 'Default Hero',
                Game_Version__c = GAME_VERSION_RED,
                Region__c = REGION_KANTO
        );
    }

    public PMHR_HeroBuilder() {
        this.record = this.defaultData();
    }

    public PMHR_HeroBuilder reset() {
        this.record = this.defaultData();
        return this;
    }

    public Hero__c build() {
        Hero__c record = this.record;
        this.reset();
        return record;
    }

    public Hero__c save() {
        Hero__c record = this.build();
        upsert record;
        return record;
    }

    public PMHR_HeroBuilder setName(String name) {
        this.record.Name = name;
        return this;
    }

    public PMHR_HeroBuilder setNickname(String nickname) {
        this.record.Nickname__c = nickname;
        return this;
    }

    public PMHR_HeroBuilder setRivalName(String rivalName) {
        this.record.Rival_Name__c = rivalName;
        return this;
    }

    public PMHR_HeroBuilder setGender(String gender) {
        this.record.Gender__c = gender;
        return this;
    }

    public PMHR_HeroBuilder setGameVersion(String gameVersion) {
        this.record.Game_Version__c = gameVersion;
        return this;
    }

    public PMHR_HeroBuilder setRegion(String region) {
        this.record.Region__c = region;
        return this;
    }
}