temp/objects/Hero__c.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                    <default>true</default>
                    <label>Male</label>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Nuzlocke__c.object
<CustomObject>
    <fields>
        <fullName>Hero__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Hero</label>
        <referenceTo>Hero__c</referenceTo>
        <relationshipLabel>Nuzlockes</relationshipLabel>
        <relationshipName>Nuzlockes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pokemon__c.object
<CustomObject>
    <fields>
        <fullName>Catch_Method__c</fullName>
        <label>Catch Method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Breeding</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Fossil</fullName>
                </value>
                <value>
                    <fullName>Game Corner</fullName>
                </value>
                <value>
                    <fullName>Headbutt</fullName>
                </value>
                <value>
                    <fullName>Land</fullName>
                </value>
                <value>
                    <fullName>Starter</fullName>
                </value>
                <value>
                    <fullName>Trade</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Caught_Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Caught Form</label>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons (Caught)</relationshipLabel>
        <relationshipName>Caught_Pokemons</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cause_of_Death__c</fullName>
        <label>Cause of Death</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Death_Level__c</fullName>
        <label>Death Level</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Death__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Death</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
        <label>Form</label>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Genderless</fullName>
                    <default>true</default>
                    <label>Genderless</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Catch Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nuzlocke__c</fullName>
        <label>Nuzlocke</label>
        <referenceTo>Nuzlocke__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Pokemon__c.object
    <fields>
        <fullName>Region_Specific_Variant__c</fullName>
        <label>Region Specific Variant</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>

src/objects/Pokemon_Data__c.object
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Pokemon_Data__c.object
    <fields>
        <fullName>Region_Specific_Variant__c</fullName>
        <label>Region Specific Variant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>

temp/objects/Pokemon_Data__c.object
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <description>Standard form of the Pokemon species</description>
        <label>Form</label>
    </recordTypes>

src/globalValueSets/Region_Specific_Pokemon_Variants.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Region Specific Pokemon Variants</masterLabel>
</GlobalValueSet>

src/classes/PMHR_PokemonBuilder_Test.cls
@IsTest
private class PMHR_PokemonBuilder_Test {
    static testMethod void shouldBuildPokemon() {
        //given
        Hero__c hero = new PMHR_HeroBuilder()
                .save();
        Nuzlocke__c nuzlocke = new PMHR_NuzlockeBuilder()
                .setHero(hero.Id)
                .save();
        Pokemon_Data__c form = new PMHR_PokemonFormBuilder()
                .save();
        Pokemon_Data__c additionalVariant = new PMHR_PokemonAdditionalVariantBuilder()
                .setVariantOf(form.Id)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .save();
        String name = 'Barry';
        String catchLocation = 'Route 1';
        String deathCause = 'Accident';
        Integer deathLevel = 5;

        //when
        Pokemon__c pokemon = new PMHR_PokemonBuilder()
                .setNuzlocke(nuzlocke.Id)
                .setCaughtForm(form.Id)
                .setName(name)
                .setForm(form.Id)
                .setGender(PMHR_Utilities.GENDER_MALE)
                .setCatchLocation(catchLocation)
                .setCatchMethod(PMHR_PokemonBuilder.CATCH_METHOD_EVENT)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .save();

        pokemon = new PMHR_PokemonBuilder(pokemon)
                .setDeath(true)
                .setDeathCause(deathCause)
                .setDeathLevel(deathLevel)
                .save();

        //then
        pokemon = PMHR_PokemonQueryService.getPokemonById(pokemon.Id);
        System.assertEquals(nuzlocke.Id, pokemon.Nuzlocke__c);
        System.assertEquals(form.Id, pokemon.Caught_Form__c);
        System.assertEquals(name, pokemon.Name);
        System.assertEquals(form.Id, pokemon.Form__c);
        System.assertEquals(PMHR_Utilities.GENDER_MALE, pokemon.Gender__c);
        System.assertEquals(catchLocation, pokemon.Location__c);
        System.assertEquals(PMHR_PokemonBuilder.CATCH_METHOD_EVENT, pokemon.Catch_Method__c);
        System.assertEquals(PMHR_Utilities.REGION_VARIANT_ALOLAN, pokemon.Region_Specific_Variant__c);
        System.assert(pokemon.Death__c);
        System.assertEquals(deathCause, pokemon.Cause_of_Death__c);
        System.assertEquals(deathLevel, Integer.valueOf(pokemon.Death_Level__c));
    }
}