temp/objects/Hero__c.object
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Nuzlocke__c.object
<CustomObject>
    <fields>
        <fullName>Allowed_Catching_Methods_Per_Area__c</fullName>
        <label>Allowed Catching Methods / Area</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Breeding (1)</fullName>
                </value>
                <value>
                    <fullName>Breeding (Any)</fullName>
                </value>
                <value>
                    <fullName>Breeding (One/Parent)</fullName>
                </value>
                <value>
                    <fullName>Breeding (One/Type)</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Fossil (1)</fullName>
                </value>
                <value>
                    <fullName>Fossil (Any)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (1)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (2)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (3)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (4)</fullName>
                </value>
                <value>
                    <fullName>Game Corner (Any)</fullName>
                </value>
                <value>
                    <fullName>Grass</fullName>
                </value>
                <value>
                    <fullName>Grass/Overworld</fullName>
                </value>
                <value>
                    <fullName>Grass/Water</fullName>
                </value>
                <value>
                    <fullName>Overworld</fullName>
                </value>
                <value>
                    <fullName>Trade</fullName>
                </value>
                <value>
                    <fullName>Tree</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Water/Tree</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Status__c</fullName>
        <label>End Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hero__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Hero</label>
        <referenceTo>Hero__c</referenceTo>
        <relationshipLabel>Nuzlockes</relationshipLabel>
        <relationshipName>Nuzlockes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legendaries_Rule__c</fullName>
        <label>Legendaries Rule</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Catch - no use</fullName>
                </value>
                <value>
                    <fullName>Catch - use</fullName>
                </value>
                <value>
                    <fullName>Kill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Multiple_Elite_Four_Fights__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if Nuzlocke run involves more than one Elite Four fights, thus assembling more than one final team</description>
        <inlineHelpText>Check, if Nuzlocke run involves more than one Elite Four fights, thus assembling more than one final team</inlineHelpText>
        <label>Multiple Elite Four Fights</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Safari_Zone_Rule__c</fullName>
        <label>Safari Zone Rule</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Amount of areas/Safari</fullName>
                </value>
                <value>
                    <fullName>One/Area</fullName>
                </value>
                <value>
                    <fullName>One/Safari</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PMHR_NuzlockeBuilder.cls
public with sharing class PMHR_NuzlockeBuilder {
    public static final String END_STATUS_SUCCESS = 'Success';
    public static final String END_STATUS_FAILED = 'Failed';

    public static final String POKEMON_CATCH_METHOD_EVENT = 'Event';

    public static final String LEGENDARIES_RULE_KILL = 'Kill';

    public static final String SAFARI_ZONE_RULE_ONE_PER_AREA = 'One/Area';

    private Nuzlocke__c record;

    private Nuzlocke__c defaultData() {
        return new Nuzlocke__c(
                Name = 'Default Nuzlocke',
                Start_Date__c = Date.today(),
                Allowed_Catching_Methods_Per_Area__c = POKEMON_CATCH_METHOD_EVENT,
                Legendaries_Rule__c = LEGENDARIES_RULE_KILL
        );
    }

    public PMHR_NuzlockeBuilder() {
        this.record = this.defaultData();
    }

    public PMHR_NuzlockeBuilder(Nuzlocke__c nuzlocke) {
        this.record = nuzlocke;
    }

    public PMHR_NuzlockeBuilder reset() {
        this.record = this.defaultData();
        return this;
    }

    public Nuzlocke__c build() {
        Nuzlocke__c record = this.record;
        this.reset();
        return record;
    }

    public Nuzlocke__c save() {
        Nuzlocke__c record = this.build();
        upsert record;
        return record;
    }

    public PMHR_NuzlockeBuilder setName(String name) {
        this.record.Name = name;
        return this;
    }

    public PMHR_NuzlockeBuilder setHero(Id heroId) {
        this.record.Hero__c = heroId;
        return this;
    }

    public PMHR_NuzlockeBuilder setAllwoedCatchMethodsPerArea(List<String> allowedCatchMethods) {
        if (allowedCatchMethods == null) {
            throw new NullAllowedCatchMethodsException();
        }
        this.record.Allowed_Catching_Methods_Per_Area__c = String.join(allowedCatchMethods, ';');
        return this;
    }

    public PMHR_NuzlockeBuilder setStartDate(Date startDate) {
        this.record.Start_Date__c = startDate;
        return this;
    }

    public PMHR_NuzlockeBuilder setLegendariesRule(String legendariesRule) {
        this.record.Legendaries_Rule__c = legendariesRule;
        return this;
    }

    public PMHR_NuzlockeBuilder setSafariZoneRule(String safariZoneRule) {
        this.record.Safari_Zone_Rule__c = safariZoneRule;
        return this;
    }

    public PMHR_NuzlockeBuilder setEndDate(Date endDate) {
        this.record.End_Date__c = endDate;
        return this;
    }

    public PMHR_NuzlockeBuilder setEndStatus(String status) {
        this.record.End_Status__c = status;
        return this;
    }

    public PMHR_NuzlockeBuilder setMultipleEliteFourFights(Boolean isMultipleEliteFourFight) {
        this.record.Multiple_Elite_Four_Fights__c = isMultipleEliteFourFight;
        return this;
    }

    public class NullAllowedCatchMethodsException extends Exception{}
}