temp/objects/Hero__c.object
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Nuzlocke__c/PMHR_Nuzlocke__c.object-meta.xml
<CustomObject>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/AllowedCatchingMethodsPerArea__c.field-meta.xml
<CustomField>
    <fullName>AllowedCatchingMethodsPerArea__c</fullName>
    <label>Allowed Catching Methods / Area</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BreedingOnlyOnce</fullName>
                <label>Breeding (Only Once)</label>
            </value>
            <value>
                <fullName>BreedingAny</fullName>
                <label>Breeding (Any)</label>
            </value>
            <value>
                <fullName>BreedingOnePerParent</fullName>
                <label>Breeding (One/Parent)</label>
            </value>
            <value>
                <fullName>BreedingOnePerType</fullName>
                <label>Breeding (One/Type)</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>FossilOnlyOne</fullName>
                <label>Fossil (Only One)</label>
            </value>
            <value>
                <fullName>FossilAny</fullName>
                <label>Fossil (Any)</label>
            </value>
            <value>
                <fullName>GameCornerMax1</fullName>
                <label>Game Corner (Max 1)</label>
            </value>
            <value>
                <fullName>GameCornerMax2</fullName>
                <label>Game Corner (Max 2)</label>
            </value>
            <value>
                <fullName>GameCornerMax3</fullName>
                <label>Game Corner (Max 3)</label>
            </value>
            <value>
                <fullName>GameCornerMax4</fullName>
                <label>Game Corner (Max 4)</label>
            </value>
            <value>
                <fullName>GameCornerAny</fullName>
                <label>Game Corner (Any)</label>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>GrassOrOverworld</fullName>
                <label>Grass/Overworld</label>
            </value>
            <value>
                <fullName>GrassOrWater</fullName>
                <label>Grass/Water</label>
            </value>
            <value>
                <fullName>Overworld</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>Tree</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>WaterOrTree</fullName>
                <label>Water/Tree</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hero</label>
    <referenceTo>PMHR_Hero__c</referenceTo>
    <relationshipLabel>Nuzlockes</relationshipLabel>
    <relationshipName>Nuzlockes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/LegendariesRule__c.field-meta.xml
<CustomField>
    <fullName>LegendariesRule__c</fullName>
    <inlineHelpText>Rules regarding the Legendary Pokemon.</inlineHelpText>
    <label>Legendaries Rule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CatchNoUse</fullName>
                <label>Catch - no use</label>
            </value>
            <value>
                <fullName>CatchUse</fullName>
                <label>Catch - use</label>
            </value>
            <value>
                <fullName>Kill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/SafariZoneRule__c.field-meta.xml
<CustomField>
    <fullName>SafariZoneRule__c</fullName>
    <label>Safari Zone Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OnePerArea</fullName>
                <label>One/Area</label>
            </value>
            <value>
                <fullName>OnePerSafari</fullName>
                <label>One/Safari</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InProgress</fullName>
                <default>true</default>
                <label>In progress</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/objectBuilders/sObjectBuilders/PMHR_NuzlockeBuilder.cls
public with sharing class PMHR_NuzlockeBuilder {
    public static final String END_STATUS_SUCCESS = 'Success';
    public static final String END_STATUS_FAILED = 'Failed';

    public static final String POKEMON_CATCH_METHOD_EVENT = 'Event';

    public static final String LEGENDARIES_RULE_KILL = 'Kill';

    public static final String SAFARI_ZONE_RULE_ONE_PER_AREA = 'One/Area';

    private PMHR_Nuzlocke__c record;

    private PMHR_Nuzlocke__c defaultData() {
        return new PMHR_Nuzlocke__c(
                Name = 'Default Nuzlocke',
                StartDate__c = Date.today(),
                AllowedCatchingMethodsPerArea__c = POKEMON_CATCH_METHOD_EVENT,
                LegendariesRule__c = LEGENDARIES_RULE_KILL
        );
    }

    public PMHR_NuzlockeBuilder() {
        this.record = this.defaultData();
    }

    public PMHR_NuzlockeBuilder(PMHR_Nuzlocke__c nuzlocke) {
        this.record = nuzlocke;
    }

    public PMHR_NuzlockeBuilder reset() {
        this.record = this.defaultData();
        return this;
    }

    public PMHR_Nuzlocke__c build() {
        PMHR_Nuzlocke__c record = this.record;
        this.reset();
        return record;
    }

    public PMHR_Nuzlocke__c save() {
        PMHR_Nuzlocke__c record = this.build();
        upsert record;
        return record;
    }

    public PMHR_NuzlockeBuilder setName(String name) {
        this.record.Name = name;
        return this;
    }

    public PMHR_NuzlockeBuilder setHero(Id heroId) {
        this.record.Hero__c = heroId;
        return this;
    }

    public PMHR_NuzlockeBuilder setAllwoedCatchMethodsPerArea(List<String> allowedCatchMethods) {
        if (allowedCatchMethods == null) {
            throw new NullAllowedCatchMethodsException();
        }
        this.record.AllowedCatchingMethodsPerArea__c = String.join(allowedCatchMethods, ';');
        return this;
    }

    public PMHR_NuzlockeBuilder setStartDate(Date startDate) {
        this.record.StartDate__c = startDate;
        return this;
    }

    public PMHR_NuzlockeBuilder setLegendariesRule(String legendariesRule) {
        this.record.LegendariesRule__c = legendariesRule;
        return this;
    }

    public PMHR_NuzlockeBuilder setSafariZoneRule(String safariZoneRule) {
        this.record.SafariZoneRule__c = safariZoneRule;
        return this;
    }

    public PMHR_NuzlockeBuilder setEndDate(Date endDate) {
        this.record.EndDate__c = endDate;
        return this;
    }

    public PMHR_NuzlockeBuilder setEndStatus(String status) {
        this.record.Status__c = status;
        return this;
    }

    public PMHR_NuzlockeBuilder setEndStatus(NuzlockeUnit.Status status) {
        this.record.Status__c = status.name();
        return this;
    }

    public PMHR_NuzlockeBuilder setMultipleEliteFourFights(Boolean isMultipleEliteFourFight) {
        this.record.Multiple_Elite_Four_Fights__c = isMultipleEliteFourFight;
        return this;
    }

    public class NullAllowedCatchMethodsException extends Exception{}
}