temp/objects/Nuzlocke__c.object
<CustomObject>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Pokemon__c/PMHR_Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Pokemon__c/fields/CatchMethod__c.field-meta.xml
<CustomField>
    <fullName>CatchMethod__c</fullName>
    <label>Catch Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Breeding</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Fossil</fullName>
            </value>
            <value>
                <fullName>GameCorner</fullName>
                <label>Game Corner</label>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Overworld</fullName>
            </value>
            <value>
                <fullName>Starter</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>Tree</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/CaughtForm__c.field-meta.xml
<CustomField>
    <fullName>CaughtForm__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Caught Form</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Pokemons (Caught)</relationshipLabel>
    <relationshipName>CaughtPokemons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/CauseOfDeath__c.field-meta.xml
<CustomField>
    <fullName>CauseOfDeath__c</fullName>
    <label>Cause of Death</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/DeathLevel__c.field-meta.xml
<CustomField>
    <fullName>DeathLevel__c</fullName>
    <label>Death Level</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
    <label>Form</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Pokemons</relationshipLabel>
    <relationshipName>Pokemons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/IsDeceased__c.field-meta.xml
<CustomField>
    <fullName>IsDeceased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deceased</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/Nuzlocke__c.field-meta.xml
<CustomField>
    <fullName>Nuzlocke__c</fullName>
    <label>Nuzlocke</label>
    <referenceTo>PMHR_Nuzlocke__c</referenceTo>
    <relationshipLabel>Pokemons</relationshipLabel>
    <relationshipName>Pokemons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PMHR_PokemonRegionalVariant.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Pokemon Regional Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/objectBuilders/sObjectBuilders/PMHR_PokemonBuilder.cls
public with sharing class PMHR_PokemonBuilder {
    public static final String CATCH_METHOD_EVENT = 'Event';

    private PMHR_Pokemon__c record;

    private PMHR_Pokemon__c defaultData() {
        return new PMHR_Pokemon__c(
                Name = 'Default Pokemon',
                Gender__c = PMHR_Utilities.GENDER_MALE,
                CatchMethod__c = 'Route 1',
                RegionalVariant__c = PMHR_Utilities.REGION_VARIANT_STANDARD
        );
    }

    public PMHR_PokemonBuilder() {
        this.record = this.defaultData();
    }

    public PMHR_PokemonBuilder(PMHR_Pokemon__c record) {
        this.record = record;
    }

    public PMHR_PokemonBuilder reset() {
        this.record = this.defaultData();
        return this;
    }

    public PMHR_Pokemon__c build() {
        PMHR_Pokemon__c record = this.record;
        this.reset();
        return record;
    }

    public PMHR_Pokemon__c save() {
        PMHR_Pokemon__c record = this.build();
        upsert record;
        return record;
    }

    public PMHR_PokemonBuilder setName(String name) {
        this.record.Name = name;
        return this;
    }

    public PMHR_PokemonBuilder setNuzlocke(Id nuzlockeId) {
        this.record.Nuzlocke__c = nuzlockeId;
        return this;
    }

    public PMHR_PokemonBuilder setCaughtForm(Id pokemonId) {
        this.record.CaughtForm__c = pokemonId;
        return this;
    }

    public PMHR_PokemonBuilder setForm(Id pokemonId) {
        this.record.Form__c = pokemonId;
        return this;
    }

    public PMHR_PokemonBuilder setCatchMethod(String catchMethod) {
        this.record.CatchMethod__c = catchMethod;
        return this;
    }

    public PMHR_PokemonBuilder setCatchLocation(String catchLocation) {
        this.record.Location__c = catchLocation;
        return this;
    }

    public PMHR_PokemonBuilder setDeath(Boolean isDeceased) {
        this.record.IsDeceased__c = isDeceased;
        return this;
    }

    public PMHR_PokemonBuilder setDeathCause(String cause) {
        this.record.CauseOfDeath__c = cause;
        return this;
    }

    public PMHR_PokemonBuilder setDeathLevel(Integer deathLevel) {
        this.record.DeathLevel__c = Decimal.valueOf(deathLevel);
        return this;
    }

    public PMHR_PokemonBuilder setGender(String gender) {
        this.record.Gender__c = gender;
        return this;
    }

    public PMHR_PokemonBuilder setRegionSpecificVariant(String variant) {
        this.record.RegionalVariant__c = String.isBlank(variant) ? PMHR_Utilities.REGION_VARIANT_STANDARD : variant;
        return this;
    }
}