temp/objects/Nuzlocke__c.object
<CustomObject>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_FinalTeam__c/PMHR_FinalTeam__c.object-meta.xml
<CustomObject>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_FinalTeam__c/fields/Nuzlocke__c.field-meta.xml
<CustomField>
    <fullName>Nuzlocke__c</fullName>
    <label>Nuzlocke</label>
    <referenceTo>PMHR_Nuzlocke__c</referenceTo>
    <relationshipLabel>Final Teams</relationshipLabel>
    <relationshipName>FinalTeams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMHR_Nuzlocke__c/PMHR_Nuzlocke__c.object-meta.xml
<CustomObject>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/triggerHandlers/PMHR_TriggerHandlerFinalTeam_Helper.cls
public class PMHR_TriggerHandlerFinalTeam_Helper {
    public static Map<Id, PMHR_Nuzlocke__c> getRelatedNuzlockes(List<PMHR_FinalTeam__c> finalTeams) {
        Set<Id> nuzlockeIds = (Set<Id>)PMHR_Utilities.fetchSObjectListToIdSet(finalTeams, PMHR_FinalTeam__c.Nuzlocke__c, false);
        return new Map<Id, PMHR_Nuzlocke__c>(PMHR_NuzlockeQueryService.getNuzlockesWithFinalTeamsByIds(nuzlockeIds));
    }
}