temp/objects/Nuzlocke__c.object
<CustomObject>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_FinalTeam__c/PMHR_FinalTeam__c.object-meta.xml
<CustomObject>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_FinalTeam__c/fields/Nuzlocke__c.field-meta.xml
<CustomField>
    <fullName>Nuzlocke__c</fullName>
    <label>Nuzlocke</label>
    <referenceTo>PMHR_Nuzlocke__c</referenceTo>
    <relationshipLabel>Final Teams</relationshipLabel>
    <relationshipName>FinalTeams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PMHR_FinalTeamBuilder.cls
public with sharing class PMHR_FinalTeamBuilder {
    private PMHR_FinalTeam__c record;

    private PMHR_FinalTeam__c defaultData() {
        return new PMHR_FinalTeam__c(
                Name = 'Default Final Team'
        );
    }

    public PMHR_FinalTeamBuilder() {
        this.record = this.defaultData();
    }

    public PMHR_FinalTeamBuilder reset() {
        this.record = this.defaultData();
        return this;
    }

    public PMHR_FinalTeam__c build() {
        PMHR_FinalTeam__c record = this.record;
        this.reset();
        return record;
    }

    public PMHR_FinalTeam__c save() {
        PMHR_FinalTeam__c record = this.build();
        upsert record;
        return record;
    }

    public PMHR_FinalTeamBuilder setName(String name) {
        this.record.Name = name;
        return this;
    }

    public PMHR_FinalTeamBuilder setNuzlocke(Id nuzlockeId) {
        this.record.Nuzlocke__c = nuzlockeId;
        return this;
    }
}