temp/objects/Pokemon_Data__c.object
<CustomObject>
    <fields>
        <fullName>Evolves_from_Variant__c</fullName>
        <description>Locks evolving into the form for region specific variants - pokemon region specific variant must correspond with provided value.</description>
        <label>Evolves from Variant</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Stage__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Family Stage</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abra</fullName>
                </value>
                <value>
                    <fullName>Absol</fullName>
                </value>
                <value>
                    <fullName>Aerodactyl</fullName>
                </value>
                <value>
                    <fullName>Aipom</fullName>
                </value>
                <value>
                    <fullName>Alomomola</fullName>
                </value>
                <value>
                    <fullName>Amaura</fullName>
                </value>
                <value>
                    <fullName>Anorith</fullName>
                </value>
                <value>
                    <fullName>Applin</fullName>
                </value>
                <value>
                    <fullName>Arceus</fullName>
                </value>
                <value>
                    <fullName>Archen</fullName>
                </value>
                <value>
                    <fullName>Arctovish</fullName>
                </value>
                <value>
                    <fullName>Arctozolt</fullName>
                </value>
                <value>
                    <fullName>Aron</fullName>
                </value>
                <value>
                    <fullName>Arrokuda</fullName>
                </value>
                <value>
                    <fullName>Articuno</fullName>
                </value>
                <value>
                    <fullName>Audino</fullName>
                </value>
                <value>
                    <fullName>Axew</fullName>
                </value>
                <value>
                    <fullName>Azelf</fullName>
                </value>
                <value>
                    <fullName>Azurill</fullName>
                </value>
                <value>
                    <fullName>Bagon</fullName>
                </value>
                <value>
                    <fullName>Baltoy</fullName>
                </value>
                <value>
                    <fullName>Barboach</fullName>
                </value>
                <value>
                    <fullName>Basculin</fullName>
                </value>
                <value>
                    <fullName>Beldum</fullName>
                </value>
                <value>
                    <fullName>Bellsprout</fullName>
                </value>
                <value>
                    <fullName>Bergmite</fullName>
                </value>
                <value>
                    <fullName>Bidoof</fullName>
                </value>
                <value>
                    <fullName>Binacle</fullName>
                </value>
                <value>
                    <fullName>Blacephalon</fullName>
                </value>
                <value>
                    <fullName>Blipbug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Picture_Url__c</fullName>
        <label>Picture Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Pokedex_Number__c</fullName>
        <defaultValue>&apos;000&apos;</defaultValue>
        <externalId>true</externalId>
        <label>Pokedex Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Type__c</fullName>
        <label>Primary Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pokemon_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region_Specific_Variant__c</fullName>
        <label>Region Specific Variant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Type__c</fullName>
        <label>Secondary Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pokemon_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Variant_Of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Variant Of</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Pokemon_Data__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Additional Variants</relationshipLabel>
        <relationshipName>Additional_Variants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <description>Standard form of the Pokemon species</description>
        <label>Form</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Pokemon_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>???</fullName>
    </customValue>
    <customValue>
        <fullName>Bug</fullName>
    </customValue>
    <customValue>
        <fullName>Dark</fullName>
    </customValue>
    <customValue>
        <fullName>Dragon</fullName>
    </customValue>
    <customValue>
        <fullName>Electric</fullName>
    </customValue>
    <customValue>
        <fullName>Fairy</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>Fire</fullName>
    </customValue>
    <customValue>
        <fullName>Flying</fullName>
    </customValue>
    <customValue>
        <fullName>Ghost</fullName>
    </customValue>
    <customValue>
        <fullName>Grass</fullName>
    </customValue>
    <customValue>
        <fullName>Ground</fullName>
    </customValue>
    <customValue>
        <fullName>Ice</fullName>
    </customValue>
    <customValue>
        <fullName>Normal</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Psychic</fullName>
    </customValue>
    <customValue>
        <fullName>Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Steel</fullName>
    </customValue>
    <customValue>
        <fullName>Water</fullName>
    </customValue>
    <description>List of all Pokemon types</description>
    <masterLabel>Pokemon Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Region_Specific_Pokemon_Variants.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Region Specific Pokemon Variants</masterLabel>
</GlobalValueSet>

temp/classes/PMHR_PokemonDataBuilder.cls
public abstract class PMHR_PokemonDataBuilder {
    public static final String RT_FORM = 'Form';
    public static final String RT_ADDITIONAL_VARIANT = 'Additional Variant';

    public static final String TYPE_NORMAL = 'Normal';
    public static final String TYPE_DARK = 'Dark';

    protected Pokemon_Data__c record;

    protected abstract Pokemon_Data__c defaultData();

    public PMHR_PokemonDataBuilder() {
        this.record = this.defaultData();
    }

    public PMHR_PokemonDataBuilder(Pokemon_Data__c pokemonDataRecord) {
        this.record = pokemonDataRecord;
    }

    public PMHR_PokemonDataBuilder reset() {
        this.record = this.defaultData();
        return this;
    }

    public Pokemon_Data__c build() {
        Pokemon_Data__c record = this.record;
        this.reset();
        return record;
    }

    public Pokemon_Data__c save() {
        Pokemon_Data__c record = this.build();
        upsert record;
        return record;
    }

    public PMHR_PokemonDataBuilder setPrimaryType(String pokemonType) {
        this.record.Primary_Type__c = pokemonType;
        return this;
    }

    public PMHR_PokemonDataBuilder setSecondaryType(String pokemonType) {
        this.record.Secondary_Type__c = pokemonType;
        return this;
    }

    public PMHR_PokemonDataBuilder setPictureUrl(String pictureUrl) {
        this.record.Picture_Url__c = pictureUrl;
        return this;
    }

    public PMHR_PokemonDataBuilder setPokedexNumber(String pokedexNumber) {
        this.record.Pokedex_Number__c = pokedexNumber;
        return this;
    }

    public PMHR_PokemonDataBuilder setForm(String form) {
        this.record.Name = form;
        return this;
    }

    public PMHR_PokemonDataBuilder setFamily(String family) {
        this.record.Family__c = family;
        return this;
    }

    public PMHR_PokemonDataBuilder setFamilyStage(Integer familyStage) {
        this.record.Family_Stage__c = Decimal.valueOf(familyStage);
        return this;
    }

    public PMHR_PokemonDataBuilder setVariantOf(Id pokemonDataId) {
        this.record.Variant_Of__c = pokemonDataId;
        return this;
    }

    public PMHR_PokemonDataBuilder setRegionSpecificVariant(String variant) {
        this.record.Region_Specific_Variant__c = variant;
        return this;
    }

    public PMHR_PokemonDataBuilder setEvolvesFromVariant(String variant) {
        this.record.Evolves_from_Variant__c = variant;
        return this;
    }
}