temp/objects/Pokemon_Data__c.object
<CustomObject>
    <fields>
        <fullName>Pokedex_Number__c</fullName>
        <defaultValue>&apos;000&apos;</defaultValue>
        <externalId>true</externalId>
        <label>Pokedex Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_Specific_Variant__c</fullName>
        <label>Region Specific Variant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region_Specific_Pokemon_Variants</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Variant_Name__c</fullName>
        <formula>TEXT(Region_Specific_Variant__c) &amp; &apos; &apos; &amp; Variant_Of__r.Name</formula>
        <label>Variant Name</label>
        <type>Text</type>
    </fields>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Region_Specific_Pokemon_Variants.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Region Specific Pokemon Variants</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PMHR_TriggerHandlerPokemonData_Test.cls
@IsTest
private class PMHR_TriggerHandlerPokemonData_Test {
    static testMethod void shouldCopyVariantNameToForm() {
        //given
        Pokemon_Data__c pokemonData = new PMHR_PokemonFormBuilder()
                .setForm('Test Data')
                .setFamily('Test Data')
                .setFamilyStage(1)
                .setPokedexNumber('000')
                .save();

        //when
        Test.startTest();
        Pokemon_Data__c additionalVariant = new PMHR_PokemonAdditionalVariantBuilder()
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .setVariantOf(pokemonData.Id)
                .save();
        Test.stopTest();

        //then
        additionalVariant = PMHR_PokemonDataQueryService.getAdditionalVariantById(additionalVariant.Id);
        System.assertEquals(additionalVariant.Name, additionalVariant.Variant_Name__c);
        System.assert(additionalVariant.Variant_Name__c.contains(pokemonData.Name));
        System.assert(additionalVariant.Variant_Name__c.contains(PMHR_Utilities.REGION_VARIANT_ALOLAN));
    }

    static testMethod void shouldNotCopyVariantNameToForm() {
        //given
        Pokemon_Data__c pokemonData = new PMHR_PokemonFormBuilder()
                .setForm('Test Data')
                .setFamily('Test Data')
                .setFamilyStage(1)
                .setPokedexNumber('000')
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .save();

        //then
        pokemonData = PMHR_PokemonDataQueryService.getPokemonFormById(pokemonData.Id);
        System.assert(!pokemonData.Name.contains(PMHR_Utilities.REGION_VARIANT_ALOLAN));
    }

    static testMethod void shouldNotCreatePokemonFormDuplicatePokedexNumber() {
        //given
        Pokemon_Data__c pokemonData = new PMHR_PokemonFormBuilder()
                .save();
        Boolean errorOccured = false;

        //when
        Test.startTest();
        try {
            new PMHR_PokemonFormBuilder()
                    .save();
        } catch (Exception ex) {
            errorOccured = true;
        }
        Test.stopTest();

        //then
        System.assertEquals(1, [SELECT Count() FROM Pokemon_Data__c]);
        System.assert(errorOccured);
    }

    static testMethod void shouldNotUpdatePokemonFormNotEditablePokedexNumber() {
        //given
        Pokemon_Data__c pokemonData = new PMHR_PokemonFormBuilder()
                .save();
        Boolean errorOccured = false;

        //when
        Test.startTest();
        try {
            pokemonData = new PMHR_PokemonFormBuilder(pokemonData)
                    .setPokedexNumber('002')
                    .save();
        } catch (Exception ex) {
            errorOccured = true;
        }
        Test.stopTest();

        //then
        Pokemon_Data__c updatedPokemonData = PMHR_PokemonDataQueryService.getPokemonFormById(pokemonData.Id);
        System.assertNotEquals(pokemonData.Pokedex_Number__c, updatedPokemonData.Pokedex_Number__c);
        System.assert(errorOccured);
    }

    static testMethod void shouldNotCreatePokemonAdditionalVariantDuplicateVariant() {
        //given
        Pokemon_Data__c pokemonData = new PMHR_PokemonFormBuilder()
                .save();
        new PMHR_PokemonAdditionalVariantBuilder()
                .setVariantOf(pokemonData.Id)
                .save();
        Boolean errorOccured = false;

        //when
        Test.startTest();
        try {
            new PMHR_PokemonAdditionalVariantBuilder()
                    .setVariantOf(pokemonData.Id)
                    .save();
        } catch (Exception ex) {
            errorOccured = true;
        }
        Test.stopTest();

        //then
        System.assertEquals(2, [SELECT Count() FROM Pokemon_Data__c]);
        System.assert(errorOccured);
    }

    static testMethod void shouldNotUpdatePokemonAdditionalVariantDuplicateVariant() {
        //given
        Pokemon_Data__c pokemonData = new PMHR_PokemonFormBuilder()
                .save();
        Pokemon_Data__c additionalVariantAlolan = new PMHR_PokemonAdditionalVariantBuilder()
                .setVariantOf(pokemonData.Id)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .build();
        Pokemon_Data__c additionalVariantGalarian = new PMHR_PokemonAdditionalVariantBuilder()
                .setVariantOf(pokemonData.Id)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_GALARIAN)
                .build();
        insert new List<Pokemon_Data__c>{additionalVariantAlolan, additionalVariantGalarian};
        Boolean errorOccured = false;

        //when
        Test.startTest();
        try {
            additionalVariantGalarian = new PMHR_PokemonAdditionalVariantBuilder(additionalVariantGalarian)
                    .setVariantOf(pokemonData.Id)
                    .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                    .save();
        } catch (Exception ex) {
            errorOccured = true;
        }
        Test.stopTest();

        //then
        additionalVariantGalarian = PMHR_PokemonDataQueryService.getAdditionalVariantById(additionalVariantGalarian.Id);
        System.assertEquals(PMHR_Utilities.REGION_VARIANT_GALARIAN, additionalVariantGalarian.Region_Specific_Variant__c);
        System.assert(errorOccured);
    }

    static testMethod void shouldDeleteAdditionalVariants() {
        //given
        Pokemon_Data__c pokemonData = new PMHR_PokemonFormBuilder()
                .save();
        Pokemon_Data__c additionalVariantAlolan = new PMHR_PokemonAdditionalVariantBuilder()
                .setVariantOf(pokemonData.Id)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .build();
        Pokemon_Data__c additionalVariantGalarian = new PMHR_PokemonAdditionalVariantBuilder()
                .setVariantOf(pokemonData.Id)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_GALARIAN)
                .build();
        insert new List<Pokemon_Data__c>{additionalVariantAlolan, additionalVariantGalarian};

        //when
        Test.startTest();
        delete pokemonData;
        Test.stopTest();

        //then
        System.assertEquals(0, [SELECT Count() FROM Pokemon_Data__c]);
    }
}