force-app/main/default/objects/PMHR_PokemonData__c/PMHR_PokemonData__c.object-meta.xml
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_PokemonData__c/fields/EvolvesFromVariant__c.field-meta.xml
<CustomField>
    <fullName>EvolvesFromVariant__c</fullName>
    <description>Locks evolving into the form for region specific variants - pokemon region specific variant must correspond with provided value.</description>
    <label>Evolves from Variant</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PrimaryType__c.field-meta.xml
<CustomField>
    <fullName>PrimaryType__c</fullName>
    <label>Primary Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PMHR_PokemonRegionalVariant.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Pokemon Regional Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/objectBuilders/sObjectBuilders/PMHR_PokemonAdditionalVariantBuilder.cls
public with sharing class PMHR_PokemonAdditionalVariantBuilder extends PMHR_PokemonDataBuilder {
    protected override PMHR_PokemonData__c defaultData() {
        return new PMHR_PokemonData__c(
                PrimaryType__c = TYPE_NORMAL,
                RegionalVariant__c = PMHR_Utilities.REGION_VARIANT_ALOLAN,
                RecordTypeId = PMHR_Utilities.getRecordTypeIdByName(SObjectType.PMHR_PokemonData__c, PMHR_PokemonDataBuilder.RT_ADDITIONAL_VARIANT),
                EvolvesFromVariant__c = PMHR_Utilities.REGION_VARIANT_STANDARD
        );
    }

    public PMHR_PokemonAdditionalVariantBuilder() {
        super();
    }

    public PMHR_PokemonAdditionalVariantBuilder(PMHR_PokemonData__c pokemonDataRecord) {
        super(pokemonDataRecord);
    }
}