force-app/main/default/objects/PMHR_PokemonData__c/PMHR_PokemonData__c.object-meta.xml
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_PokemonData__c/fields/EvolvesFromVariant__c.field-meta.xml
<CustomField>
    <fullName>EvolvesFromVariant__c</fullName>
    <description>Locks evolving into the form for region specific variants - pokemon region specific variant must correspond with provided value.</description>
    <label>Evolves from Variant</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abra</fullName>
            </value>
            <value>
                <fullName>Absol</fullName>
            </value>
            <value>
                <fullName>Aerodactyl</fullName>
            </value>
            <value>
                <fullName>Aipom</fullName>
            </value>
            <value>
                <fullName>Alomomola</fullName>
            </value>
            <value>
                <fullName>Amaura</fullName>
            </value>
            <value>
                <fullName>Anorith</fullName>
            </value>
            <value>
                <fullName>Applin</fullName>
            </value>
            <value>
                <fullName>Arceus</fullName>
            </value>
            <value>
                <fullName>Archen</fullName>
            </value>
            <value>
                <fullName>Arctovish</fullName>
            </value>
            <value>
                <fullName>Arctozolt</fullName>
            </value>
            <value>
                <fullName>Aron</fullName>
            </value>
            <value>
                <fullName>Arrokuda</fullName>
            </value>
            <value>
                <fullName>Articuno</fullName>
            </value>
            <value>
                <fullName>Audino</fullName>
            </value>
            <value>
                <fullName>Axew</fullName>
            </value>
            <value>
                <fullName>Azelf</fullName>
            </value>
            <value>
                <fullName>Azurill</fullName>
            </value>
            <value>
                <fullName>Bagon</fullName>
            </value>
            <value>
                <fullName>Baltoy</fullName>
            </value>
            <value>
                <fullName>Barboach</fullName>
            </value>
            <value>
                <fullName>Basculin</fullName>
            </value>
            <value>
                <fullName>Beldum</fullName>
            </value>
            <value>
                <fullName>Bellsprout</fullName>
            </value>
            <value>
                <fullName>Bergmite</fullName>
            </value>
            <value>
                <fullName>Bidoof</fullName>
            </value>
            <value>
                <fullName>Binacle</fullName>
            </value>
            <value>
                <fullName>Blacephalon</fullName>
            </value>
            <value>
                <fullName>Blipbug</fullName>
            </value>
            <value>
                <fullName>Bulbasaur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/FamilyStage__c.field-meta.xml
<CustomField>
    <fullName>FamilyStage__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Family Stage</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PictureUrl__c.field-meta.xml
<CustomField>
    <fullName>PictureUrl__c</fullName>
    <label>Picture Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PokedexNumber__c.field-meta.xml
<CustomField>
    <fullName>PokedexNumber__c</fullName>
    <defaultValue>&apos;000&apos;</defaultValue>
    <externalId>true</externalId>
    <label>Pokedex Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PrimaryType__c.field-meta.xml
<CustomField>
    <fullName>PrimaryType__c</fullName>
    <label>Primary Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/SecondaryType__c.field-meta.xml
<CustomField>
    <fullName>SecondaryType__c</fullName>
    <label>Secondary Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/VariantName__c.field-meta.xml
<CustomField>
    <fullName>VariantName__c</fullName>
    <formula>TEXT(RegionalVariant__c) &amp; &apos; &apos; &amp; VariantOf__r.Name</formula>
    <label>Variant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/VariantOf__c.field-meta.xml
<CustomField>
    <fullName>VariantOf__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant of</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/recordTypes/Form.recordType-meta.xml
<RecordType>
    <fullName>Form</fullName>
    <active>true</active>
    <description>Standard form of the Pokemon species</description>
    <label>Form</label>
</RecordType>

force-app/main/default/globalValueSets/PMHR_PokemonRegionalVariant.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Pokemon Regional Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/objectBuilders/sObjectBuilders/PMHR_PokemonDataBuilder_Test.cls
@IsTest
private class PMHR_PokemonDataBuilder_Test {
    static testMethod void shouldBuildPokemonForm() {
        //given
        String form = 'Bulbasaur';
        String pokedexNumber = '001';
        Integer familyStage = 1;
        String pictureUrl = 'https://test.picture.com';

        List<String> regionSpecificVariants = PMHR_Utilities.getPokemonRegionalVariantsValues();

        //when
        PMHR_PokemonData__c pokemonData = new PMHR_PokemonFormBuilder()
                .setPokedexNumber(pokedexNumber)
                .setForm(form)
                .setFamily(form)
                .setFamilyStage(familyStage)
                .setPrimaryType(PMHR_PokemonDataBuilder.TYPE_NORMAL)
                .setSecondaryType(PMHR_PokemonDataBuilder.TYPE_DARK)
                .setPictureUrl(pictureUrl)
                .setEvolvesFromVariant(PMHR_Utilities.REGION_VARIANT_STANDARD)
                .save();

        //then
        pokemonData = PMHR_PokemonDataQueryService.getPokemonFormById(pokemonData.Id);
        System.assertEquals(form, pokemonData.Name);
        System.assertEquals(pokedexNumber, pokemonData.PokedexNumber__c);
        System.assertEquals(form, pokemonData.Family__c);
        System.assertEquals(familyStage, Integer.valueOf(pokemonData.FamilyStage__c));
        System.assertEquals(PMHR_PokemonDataBuilder.TYPE_NORMAL, pokemonData.PrimaryType__c);
        System.assertEquals(PMHR_PokemonDataBuilder.TYPE_DARK, pokemonData.SecondaryType__c);
        System.assertEquals(pictureUrl, pokemonData.PictureUrl__c);
        System.assertEquals(pictureUrl, pokemonData.PictureUrl__c);
        System.assertEquals(PMHR_Utilities.REGION_VARIANT_STANDARD, pokemonData.EvolvesFromVariant__c);
    }

    static testMethod void shouldBuildPokemonAdditionalVariant() {
        //given
        String pictureUrl = 'https://test.picture.com';
        PMHR_PokemonData__c pokemonForm = new PMHR_PokemonFormBuilder()
                .save();

        //when
        PMHR_PokemonData__c additionalVariant = new PMHR_PokemonAdditionalVariantBuilder()
                .setVariantOf(pokemonForm.Id)
                .setRegionSpecificVariant(PMHR_Utilities.REGION_VARIANT_ALOLAN)
                .setPrimaryType(PMHR_PokemonDataBuilder.TYPE_DARK)
                .setPictureUrl(pictureUrl)
                .save();

        //then
        additionalVariant = PMHR_PokemonDataQueryService.getAdditionalVariantById(additionalVariant.Id);
        System.assertEquals(pokemonForm.Id, additionalVariant.VariantOf__c);
        System.assertEquals(PMHR_Utilities.REGION_VARIANT_ALOLAN, additionalVariant.RegionalVariant__c);
        System.assertEquals(PMHR_PokemonDataBuilder.TYPE_DARK, additionalVariant.PrimaryType__c);
        System.assertEquals(additionalVariant.VariantName__c, additionalVariant.Name);
        System.assert(additionalVariant.Name.contains(pokemonForm.Name));
        System.assert(additionalVariant.Name.contains(PMHR_Utilities.REGION_VARIANT_ALOLAN));
    }
}