force-app/main/default/objects/PMHR_PokemonData__c/PMHR_PokemonData__c.object-meta.xml
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_PokemonData__c/fields/EvolvesFromVariant__c.field-meta.xml
<CustomField>
    <fullName>EvolvesFromVariant__c</fullName>
    <description>Locks evolving into the form for region specific variants - pokemon region specific variant must correspond with provided value.</description>
    <label>Evolves from Variant</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abra</fullName>
            </value>
            <value>
                <fullName>Absol</fullName>
            </value>
            <value>
                <fullName>Aerodactyl</fullName>
            </value>
            <value>
                <fullName>Aipom</fullName>
            </value>
            <value>
                <fullName>Alomomola</fullName>
            </value>
            <value>
                <fullName>Amaura</fullName>
            </value>
            <value>
                <fullName>Anorith</fullName>
            </value>
            <value>
                <fullName>Applin</fullName>
            </value>
            <value>
                <fullName>Arceus</fullName>
            </value>
            <value>
                <fullName>Archen</fullName>
            </value>
            <value>
                <fullName>Arctovish</fullName>
            </value>
            <value>
                <fullName>Arctozolt</fullName>
            </value>
            <value>
                <fullName>Aron</fullName>
            </value>
            <value>
                <fullName>Arrokuda</fullName>
            </value>
            <value>
                <fullName>Articuno</fullName>
            </value>
            <value>
                <fullName>Audino</fullName>
            </value>
            <value>
                <fullName>Axew</fullName>
            </value>
            <value>
                <fullName>Azelf</fullName>
            </value>
            <value>
                <fullName>Azurill</fullName>
            </value>
            <value>
                <fullName>Bagon</fullName>
            </value>
            <value>
                <fullName>Baltoy</fullName>
            </value>
            <value>
                <fullName>Barboach</fullName>
            </value>
            <value>
                <fullName>Basculin</fullName>
            </value>
            <value>
                <fullName>Beldum</fullName>
            </value>
            <value>
                <fullName>Bellsprout</fullName>
            </value>
            <value>
                <fullName>Bergmite</fullName>
            </value>
            <value>
                <fullName>Bidoof</fullName>
            </value>
            <value>
                <fullName>Binacle</fullName>
            </value>
            <value>
                <fullName>Blacephalon</fullName>
            </value>
            <value>
                <fullName>Blipbug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/FamilyStage__c.field-meta.xml
<CustomField>
    <fullName>FamilyStage__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Family Stage</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PokedexNumber__c.field-meta.xml
<CustomField>
    <fullName>PokedexNumber__c</fullName>
    <defaultValue>&apos;000&apos;</defaultValue>
    <externalId>true</externalId>
    <label>Pokedex Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PrimaryType__c.field-meta.xml
<CustomField>
    <fullName>PrimaryType__c</fullName>
    <label>Primary Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PMHR_PokemonRegionalVariant.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Pokemon Regional Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/objectBuilders/sObjectBuilders/PMHR_PokemonFormBuilder.cls
public with sharing class PMHR_PokemonFormBuilder extends PMHR_PokemonDataBuilder {
    protected override PMHR_PokemonData__c defaultData() {
        return new PMHR_PokemonData__c(
                PokedexNumber__c = '001',
                Name = 'Default Pokemon',
                PrimaryType__c = TYPE_NORMAL,
                Family__c = 'Default Pokemon',
                FamilyStage__c = 1,
                RecordTypeId = PMHR_Utilities.getRecordTypeIdByName(SObjectType.PMHR_PokemonData__c, PMHR_PokemonDataBuilder.RT_FORM),
                EvolvesFromVariant__c = PMHR_Utilities.REGION_VARIANT_STANDARD
        );
    }

    public PMHR_PokemonFormBuilder() {
        super();
    }

    public PMHR_PokemonFormBuilder(PMHR_PokemonData__c pokemonDataRecord) {
        super(pokemonDataRecord);
    }
}