force-app/main/default/objects/PMHR_PokemonData__c/PMHR_PokemonData__c.object-meta.xml
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_PokemonData__c/fields/EvolvesFromVariant__c.field-meta.xml
<CustomField>
    <fullName>EvolvesFromVariant__c</fullName>
    <description>Locks evolving into the form for region specific variants - pokemon region specific variant must correspond with provided value.</description>
    <label>Evolves from Variant</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abra</fullName>
            </value>
            <value>
                <fullName>Absol</fullName>
            </value>
            <value>
                <fullName>Aerodactyl</fullName>
            </value>
            <value>
                <fullName>Aipom</fullName>
            </value>
            <value>
                <fullName>Alomomola</fullName>
            </value>
            <value>
                <fullName>Amaura</fullName>
            </value>
            <value>
                <fullName>Anorith</fullName>
            </value>
            <value>
                <fullName>Applin</fullName>
            </value>
            <value>
                <fullName>Arceus</fullName>
            </value>
            <value>
                <fullName>Archen</fullName>
            </value>
            <value>
                <fullName>Arctovish</fullName>
            </value>
            <value>
                <fullName>Arctozolt</fullName>
            </value>
            <value>
                <fullName>Aron</fullName>
            </value>
            <value>
                <fullName>Arrokuda</fullName>
            </value>
            <value>
                <fullName>Articuno</fullName>
            </value>
            <value>
                <fullName>Audino</fullName>
            </value>
            <value>
                <fullName>Axew</fullName>
            </value>
            <value>
                <fullName>Azelf</fullName>
            </value>
            <value>
                <fullName>Azurill</fullName>
            </value>
            <value>
                <fullName>Bagon</fullName>
            </value>
            <value>
                <fullName>Baltoy</fullName>
            </value>
            <value>
                <fullName>Barboach</fullName>
            </value>
            <value>
                <fullName>Basculin</fullName>
            </value>
            <value>
                <fullName>Beldum</fullName>
            </value>
            <value>
                <fullName>Bellsprout</fullName>
            </value>
            <value>
                <fullName>Bergmite</fullName>
            </value>
            <value>
                <fullName>Bidoof</fullName>
            </value>
            <value>
                <fullName>Binacle</fullName>
            </value>
            <value>
                <fullName>Blacephalon</fullName>
            </value>
            <value>
                <fullName>Blipbug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/FamilyStage__c.field-meta.xml
<CustomField>
    <fullName>FamilyStage__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Family Stage</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PictureUrl__c.field-meta.xml
<CustomField>
    <fullName>PictureUrl__c</fullName>
    <label>Picture Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PokedexNumber__c.field-meta.xml
<CustomField>
    <fullName>PokedexNumber__c</fullName>
    <defaultValue>&apos;000&apos;</defaultValue>
    <externalId>true</externalId>
    <label>Pokedex Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PrimaryType__c.field-meta.xml
<CustomField>
    <fullName>PrimaryType__c</fullName>
    <label>Primary Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/SecondaryType__c.field-meta.xml
<CustomField>
    <fullName>SecondaryType__c</fullName>
    <label>Secondary Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/VariantOf__c.field-meta.xml
<CustomField>
    <fullName>VariantOf__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant of</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/recordTypes/Form.recordType-meta.xml
<RecordType>
    <fullName>Form</fullName>
    <active>true</active>
    <description>Standard form of the Pokemon species</description>
    <label>Form</label>
</RecordType>

force-app/main/default/objects/PMHR_PokemonData__c/recordTypes/Variant.recordType-meta.xml
<RecordType>
    <fullName>Variant</fullName>
    <active>true</active>
    <description>Additional variant of Pokemon form, like Alolan or Galarian.</description>
    <label>Variant</label>
</RecordType>

force-app/main/default/globalValueSets/PMHR_PokemonRegionalVariant.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Pokemon Regional Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PMHR_PokemonDataBuilder.cls
public abstract class PMHR_PokemonDataBuilder {
    public static final String RT_FORM = 'Form';
    public static final String RT_ADDITIONAL_VARIANT = 'Additional Variant';

    public static final String TYPE_NORMAL = 'Normal';
    public static final String TYPE_DARK = 'Dark';

    protected PMHR_PokemonData__c record;

    protected abstract PMHR_PokemonData__c defaultData();

    public PMHR_PokemonDataBuilder() {
        this.record = this.defaultData();
    }

    public PMHR_PokemonDataBuilder(PMHR_PokemonData__c pokemonDataRecord) {
        this.record = pokemonDataRecord;
    }

    public PMHR_PokemonDataBuilder reset() {
        this.record = this.defaultData();
        return this;
    }

    public PMHR_PokemonData__c build() {
        PMHR_PokemonData__c record = this.record;
        this.reset();
        return record;
    }

    public PMHR_PokemonData__c save() {
        PMHR_PokemonData__c record = this.build();
        upsert record;
        return record;
    }

    public PMHR_PokemonDataBuilder setPrimaryType(String pokemonType) {
        this.record.PrimaryType__c = pokemonType;
        return this;
    }

    public PMHR_PokemonDataBuilder setSecondaryType(String pokemonType) {
        this.record.SecondaryType__c = pokemonType;
        return this;
    }

    public PMHR_PokemonDataBuilder setPictureUrl(String pictureUrl) {
        this.record.PictureUrl__c = pictureUrl;
        return this;
    }

    public PMHR_PokemonDataBuilder setPokedexNumber(String pokedexNumber) {
        this.record.PokedexNumber__c = pokedexNumber;
        return this;
    }

    public PMHR_PokemonDataBuilder setForm(String form) {
        this.record.Name = form;
        return this;
    }

    public PMHR_PokemonDataBuilder setFamily(String family) {
        this.record.Family__c = family;
        return this;
    }

    public PMHR_PokemonDataBuilder setFamilyStage(Integer familyStage) {
        this.record.FamilyStage__c = Decimal.valueOf(familyStage);
        return this;
    }

    public PMHR_PokemonDataBuilder setVariantOf(Id pokemonDataId) {
        this.record.VariantOf__c = pokemonDataId;
        return this;
    }

    public PMHR_PokemonDataBuilder setRegionSpecificVariant(String variant) {
        this.record.RegionalVariant__c = variant;
        return this;
    }

    public PMHR_PokemonDataBuilder setEvolvesFromVariant(String variant) {
        this.record.EvolvesFromVariant__c = variant;
        return this;
    }
}