force-app/main/default/objects/PMHR_PokemonData__c/PMHR_PokemonData__c.object-meta.xml
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_PokemonData__c/fields/PokedexNumber__c.field-meta.xml
<CustomField>
    <fullName>PokedexNumber__c</fullName>
    <defaultValue>&apos;000&apos;</defaultValue>
    <externalId>true</externalId>
    <label>Pokedex Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/RegionalVariant__c.field-meta.xml
<CustomField>
    <fullName>RegionalVariant__c</fullName>
    <label>Regional Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMHR_PokemonRegionalVariant</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/VariantName__c.field-meta.xml
<CustomField>
    <fullName>VariantName__c</fullName>
    <formula>TEXT(RegionalVariant__c) &amp; &apos; &apos; &amp; VariantOf__r.Name</formula>
    <label>Variant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_PokemonData__c/fields/VariantOf__c.field-meta.xml
<CustomField>
    <fullName>VariantOf__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant of</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/PMHR_PokemonRegionalVariant.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Alolan</fullName>
    </customValue>
    <customValue>
        <fullName>Galarian</fullName>
    </customValue>
    <masterLabel>Pokemon Regional Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/triggerHandlers/PMHR_TriggerHandlerPokemonData_Helper.cls
public with sharing class PMHR_TriggerHandlerPokemonData_Helper {

    public static Set<Id> getPokemonDataIds(List<PMHR_PokemonData__c> pokemonData, SObjectField field) {
        return PMHR_Utilities.fetchSObjectListToIdSet(pokemonData, field, false);
    }

    public static Set<String> getPokemonPokedexNumbers(List<PMHR_PokemonData__c> pokemonData) {
        return PMHR_Utilities.fetchSObjectListToStringSet(pokemonData, PMHR_PokemonData__c.PokedexNumber__c, false);
    }

    public static List<PMHR_PokemonData__c> getExistingPokemonData(Set<Id> pokemonDataIds, Set<String> pokedexNumbers) {
        return PMHR_PokemonDataQueryService.getPokemonFormByIdsOrPokedexNumbers(pokemonDataIds, pokedexNumbers);
    }

    public static List<PMHR_PokemonData__c> getExistingPokemonAdditionalVariants(Set<Id> pokemonDataIds) {
        return PMHR_PokemonDataQueryService.getAdditionalVariantByFormIds(pokemonDataIds);
    }

    public static void validateDuplicatePokedexNumber(PMHR_PokemonData__c pokemonForm, Set<String> existingPokedexNumbers) {
        if (String.isNotBlank(pokemonForm.PokedexNumber__c) && existingPokedexNumbers.contains(pokemonForm.PokedexNumber__c)) {
            pokemonForm.PokedexNumber__c.addError(System.Label.PMHR_Duplicate_Value_Error);
        }
    }

    public static void validateDuplicateRegionSpecificVariant(PMHR_PokemonData__c additionalVariant, Map<Id, PMHR_PokemonData__c> existingPokemonForms) {
        if (String.isNotBlank(additionalVariant.RegionalVariant__c)) {
            PMHR_PokemonData__c pokemonForm = existingPokemonForms.get(additionalVariant.VariantOf__c);
            for (PMHR_PokemonData__c existingAdditionalVariant : pokemonForm.Variants__r) {
                if (existingAdditionalVariant.RegionalVariant__c == additionalVariant.RegionalVariant__c
                        && existingAdditionalVariant.Id != additionalVariant.Id) {
                    additionalVariant.RegionalVariant__c.addError(System.Label.PMHR_Duplicate_Value_Error);
                }
            }
        }
    }

    public static void copyVariantNameToForm(PMHR_PokemonData__c additionalVariant) {
        additionalVariant = new PMHR_PokemonAdditionalVariantBuilder(additionalVariant)
                .setForm(additionalVariant.VariantName__c)
                .build();
    }
}