force-app/main/default/objects/PMHR_FinalTeam__c/PMHR_FinalTeam__c.object-meta.xml
<CustomObject>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_FinalTeamMember__c/PMHR_FinalTeamMember__c.object-meta.xml
<CustomObject>
    <label>Final Team Member</label>
    <nameField>
        <displayFormat>FTM-{000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Ability__c.field-meta.xml
<CustomField>
    <fullName>Ability__c</fullName>
    <label>Ability</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/FinalTeam__c.field-meta.xml
<CustomField>
    <fullName>FinalTeam__c</fullName>
    <label>Final Team</label>
    <referenceTo>PMHR_FinalTeam__c</referenceTo>
    <relationshipLabel>Final Team Members</relationshipLabel>
    <relationshipName>FinalTeamMembers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/HeldItem__c.field-meta.xml
<CustomField>
    <fullName>HeldItem__c</fullName>
    <label>Held Item</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Move1__c.field-meta.xml
<CustomField>
    <fullName>Move1__c</fullName>
    <label>Move 1</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Move2__c.field-meta.xml
<CustomField>
    <fullName>Move2__c</fullName>
    <label>Move 2</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Move3__c.field-meta.xml
<CustomField>
    <fullName>Move3__c</fullName>
    <label>Move 3</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Move4__c.field-meta.xml
<CustomField>
    <fullName>Move4__c</fullName>
    <label>Move 4</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Nature__c.field-meta.xml
<CustomField>
    <fullName>Nature__c</fullName>
    <label>Nature</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokemon</label>
    <referenceTo>PMHR_Pokemon__c</referenceTo>
    <relationshipLabel>Final Team Members</relationshipLabel>
    <relationshipName>FinalTeamMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMHR_Hero__c/PMHR_Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Nuzlocke__c/PMHR_Nuzlocke__c.object-meta.xml
<CustomObject>
    <label>Nuzlocke</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nuzlockes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Pokemon__c/PMHR_Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_PokemonData__c/PMHR_PokemonData__c.object-meta.xml
<CustomObject>
    <label>Pokemon Data</label>
    <nameField>
        <label>Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Pokemon__c.object
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/objectBuilders/sObjectBuilders/PMHR_FinalTeamMemberBuilder_Test.cls
@IsTest
private class PMHR_FinalTeamMemberBuilder_Test {
    static testMethod void shouldBuildFinalTeamMember() {
        //given
        String ability = 'Blaze';
        String nature = 'Calm';
        String heldItem = 'Quick Claw';
        Integer level = 65;
        String move1 = 'Tackle';
        String move2 = 'Flamethrower';
        String move3 = 'Toxic';
        String move4 = 'Roar';

        Map<Integer, String> moves = new Map<Integer, String> {
                1 => move1,
                2 => move2,
                3 => move3,
                4 => move4
        };

        PMHR_Hero__c hero = new PMHR_HeroBuilder()
                .save();
        PMHR_Nuzlocke__c nuzlocke = new PMHR_NuzlockeBuilder()
                .setHero(hero.Id)
                .save();
        PMHR_PokemonData__c pokemonData = new PMHR_PokemonFormBuilder()
                .save();
        PMHR_Pokemon__c pokemon = new PMHR_PokemonBuilder()
                .setNuzlocke(nuzlocke.Id)
                .setCaughtForm(pokemonData.Id)
                .save();
        PMHR_FinalTeam__c finalTeam = new PMHR_FinalTeamBuilder()
                .setNuzlocke(nuzlocke.Id)
                .save();

        //when
        PMHR_FinalTeamMember__c member = new PMHR_FinalTeamMemberBuilder()
                .setPokemon(pokemon.Id)
                .setFinalTeam(finalTeam.Id)
                .setAbility(ability)
                .setNature(nature)
                .setHeldItem(heldItem)
                .setLevel(level)
                .setMoves(moves)
                .save();

        //then
        member = PMHR_FinalTeamMemberQueryService.getFinalTeamMemberById(member.Id);
        System.assertEquals(pokemon.Id, member.Pokemon__c);
        System.assertEquals(finalTeam.Id, member.FinalTeam__c);
        System.assertEquals(ability, member.Ability__c);
        System.assertEquals(nature, member.Nature__c);
        System.assertEquals(heldItem, member.HeldItem__c);
        System.assertEquals(level, Integer.valueOf(member.Level__c));
        System.assertEquals(move1, member.Move1__c);
        System.assertEquals(move2, member.Move2__c);
        System.assertEquals(move3, member.Move3__c);
        System.assertEquals(move4, member.Move4__c);
    }

    static testMethod void shouldThrowExceptionToManyMoves() {
        //given
        Map<Integer, String> moves = new Map<Integer, String> {
                1 => 'move1',
                2 => 'move2',
                3 => 'move3',
                4 => 'move4',
                5 => 'move5'
        };
        Boolean errorOccurred = false;

        //when
        try {
            PMHR_FinalTeamMember__c member = new PMHR_FinalTeamMemberBuilder()
                    .setMoves(moves)
                    .build();
        } catch (PMHR_FinalTeamMemberBuilder.InvalidNumberOfMovesException ex) {
            errorOccurred = true;
        }

        //then
        System.assert(errorOccurred);
    }

    static testMethod void shouldThrowExceptionToNullMoves() {
        //given
        Boolean errorOccurred = false;

        //when
        try {
            PMHR_FinalTeamMember__c member = new PMHR_FinalTeamMemberBuilder()
                    .setMoves(null)
                    .build();
        } catch (PMHR_FinalTeamMemberBuilder.InvalidNumberOfMovesException ex) {
            errorOccurred = true;
        }

        //then
        System.assert(errorOccurred);
    }

    static testMethod void shouldThrowExceptionInvalidMoveNumber() {
        //given
        Map<Integer, String> moves = new Map<Integer, String> {
                5 => 'move5'
        };
        Boolean errorOccurred = false;

        //when
        try {
            PMHR_FinalTeamMember__c member = new PMHR_FinalTeamMemberBuilder()
                    .setMoves(moves)
                    .build();
        } catch (PMHR_FinalTeamMemberBuilder.InvalidMoveNumberException ex) {
            errorOccurred = true;
        }

        //then
        System.assert(errorOccurred);
    }
}