force-app/main/default/objects/PMHR_FinalTeam__c/PMHR_FinalTeam__c.object-meta.xml
<CustomObject>
    <label>Final Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Final Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_FinalTeamMember__c/PMHR_FinalTeamMember__c.object-meta.xml
<CustomObject>
    <label>Final Team Member</label>
    <nameField>
        <displayFormat>FTM-{000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/FinalTeam__c.field-meta.xml
<CustomField>
    <fullName>FinalTeam__c</fullName>
    <label>Final Team</label>
    <referenceTo>PMHR_FinalTeam__c</referenceTo>
    <relationshipLabel>Final Team Members</relationshipLabel>
    <relationshipName>FinalTeamMembers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokemon</label>
    <referenceTo>PMHR_Pokemon__c</referenceTo>
    <relationshipLabel>Final Team Members</relationshipLabel>
    <relationshipName>FinalTeamMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMHR_FinalTeamMember__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>Pokemon__r.Form__r.Type__c</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMHR_Pokemon__c/PMHR_Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMHR_Pokemon__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
    <label>Form</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMHR_PokemonData__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Form</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMHR_PokemonData__c</referenceTo>
    <relationshipLabel>Pokemons</relationshipLabel>
    <relationshipName>Pokemons</relationshipName>
    <type>Lookup</type>
</CustomField>

temp/objects/Pokemon__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>If you&apos;re creating a new Pokemon this field will be filled automatically</inlineHelpText>
        <label>Form</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Pokemon_Data__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pokemon_Data__c</referenceTo>
        <relationshipLabel>Pokemons</relationshipLabel>
        <relationshipName>Pokemons</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pokemon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/lwcControllers/PMHR_FinalTeamListControllerHelper.cls
public with sharing class PMHR_FinalTeamListControllerHelper {
    private static PMHR_FinalTeamListControllerHelper instance;

    private PMHR_FinalTeamListControllerHelper() {}

    public static PMHR_FinalTeamListControllerHelper getInstance() {
        if (instance == null) {
            instance = new PMHR_FinalTeamListControllerHelper();
        }
        return instance;
    }

    public List<FinalTeam> parseFinalTeams(List<PMHR_FinalTeam__c> finalTeamsToParse) {
        List<FinalTeam> result = new List<FinalTeam>();

        for (PMHR_FinalTeam__c finalTeam : finalTeamsToParse) {
            List<FinalTeamMember> finalTeamMembers = new List<FinalTeamMember>();
            for (PMHR_FinalTeamMember__c member : finalTeam.FinalTeamMembers__r) {
                finalTeamMembers.add(new FinalTeamMember(member));
            }

            result.add(new FinalTeam(finalTeam, finalTeamMembers));
        }

        return result.isEmpty() ? null : result;
    }

    public class FinalTeam {
        @AuraEnabled public Id id { get; private set; }
        @AuraEnabled public String name { get; private set; }
        @AuraEnabled public List<FinalTeamMember> members { get; private set; }

        public FinalTeam(PMHR_FinalTeam__c finalTeam, List<FinalTeamMember> members) {
            this.id = finalTeam.Id;
            this.name = finalTeam.Name;
            this.members = members;
        }
    }

    public class FinalTeamMember {
        @AuraEnabled public Id id { get; private set; }
        @AuraEnabled public String nr { get; private set; }
        @AuraEnabled public String pokemonName { get; private set; }
        @AuraEnabled public Id pokemonId { get; private set; }
        @AuraEnabled public String form { get; private set; }
        @AuraEnabled public String type { get; private set; }
        @AuraEnabled public Integer level { get; private set; }

        public FinalTeamMember(PMHR_FinalTeamMember__c member) {
            this.id = member.Id;
            this.nr = member.Name;
            this.pokemonName = member.Pokemon__r.Name;
            this.pokemonId = member.Pokemon__c;
            this.form = member.Form__c;
            this.type = member.Type__c;
            this.level = Integer.valueOf(member.Level__c);
        }
    }
}